# Generated by sgb2ns, created by Polly Huang
# GRAPH (#nodes #edges id uu vv ww xx yy zz):
# 1040 3030 transtub(0,3,0,0,{16,288,3,1.000,0.000,0.000},{5,144,3,0.600,0.000,0.000},{4,89,3,0.420,0.000,0.000}) 288 4 4 1 

proc create-topology {nsns node linkBW} {
	upvar $node n
	upvar $nsns ns

	set verbose 1

	if {$verbose} { 
		puts "creating nodes..." 
}
		for {set i 0} {$i < 1040} {incr i} {
			set n($i) [$ns node]
	}

	# EDGES (from-node to-node length a b):
	if {$verbose} { 
		puts -nonewline "Creating links 0..."
		flush stdout 
	}
	$ns duplex-link $n(0) $n(144) $linkBW 1810ms DropTail
	$ns duplex-link $n(0) $n(340) $linkBW 2280ms DropTail
	$ns duplex-link $n(0) $n(819) $linkBW 1380ms DropTail
	$ns duplex-link $n(0) $n(1001) $linkBW 690ms DropTail
	$ns duplex-link $n(0) $n(13) $linkBW 110ms DropTail
	$ns duplex-link $n(0) $n(7) $linkBW 680ms DropTail
	$ns duplex-link $n(0) $n(1) $linkBW 1340ms DropTail
	$ns duplex-link $n(0) $n(5) $linkBW 1590ms DropTail
	$ns duplex-link $n(1) $n(1003) $linkBW 1380ms DropTail
	$ns duplex-link $n(1) $n(611) $linkBW 2050ms DropTail
	if {$verbose} { puts -nonewline "10..."; flush stdout }
	$ns duplex-link $n(1) $n(472) $linkBW 1590ms DropTail
	$ns duplex-link $n(1) $n(79) $linkBW 2030ms DropTail
	$ns duplex-link $n(1) $n(682) $linkBW 1670ms DropTail
	$ns duplex-link $n(1) $n(793) $linkBW 1290ms DropTail
	$ns duplex-link $n(1) $n(28) $linkBW 490ms DropTail
	$ns duplex-link $n(1) $n(21) $linkBW 970ms DropTail
	$ns duplex-link $n(1) $n(19) $linkBW 530ms DropTail
	$ns duplex-link $n(1) $n(14) $linkBW 230ms DropTail
	$ns duplex-link $n(1) $n(2) $linkBW 250ms DropTail
	$ns duplex-link $n(1) $n(3) $linkBW 150ms DropTail
	if {$verbose} { puts -nonewline "20..."; flush stdout }
	$ns duplex-link $n(1) $n(4) $linkBW 600ms DropTail
	$ns duplex-link $n(2) $n(951) $linkBW 3070ms DropTail
	$ns duplex-link $n(2) $n(344) $linkBW 3290ms DropTail
	$ns duplex-link $n(2) $n(277) $linkBW 2620ms DropTail
	$ns duplex-link $n(2) $n(147) $linkBW 2540ms DropTail
	$ns duplex-link $n(2) $n(534) $linkBW 2850ms DropTail
	$ns duplex-link $n(2) $n(624) $linkBW 2500ms DropTail
	$ns duplex-link $n(2) $n(951) $linkBW 3070ms DropTail
	$ns duplex-link $n(2) $n(44) $linkBW 530ms DropTail
	$ns duplex-link $n(2) $n(40) $linkBW 750ms DropTail
	if {$verbose} { puts -nonewline "30..."; flush stdout }
	$ns duplex-link $n(2) $n(34) $linkBW 750ms DropTail
	$ns duplex-link $n(2) $n(33) $linkBW 150ms DropTail
	$ns duplex-link $n(2) $n(4) $linkBW 630ms DropTail
	$ns duplex-link $n(2) $n(5) $linkBW 810ms DropTail
	$ns duplex-link $n(3) $n(874) $linkBW 2170ms DropTail
	$ns duplex-link $n(3) $n(624) $linkBW 2150ms DropTail
	$ns duplex-link $n(3) $n(537) $linkBW 2470ms DropTail
	$ns duplex-link $n(3) $n(209) $linkBW 1070ms DropTail
	$ns duplex-link $n(3) $n(274) $linkBW 2410ms DropTail
	$ns duplex-link $n(3) $n(469) $linkBW 1900ms DropTail
	if {$verbose} { puts -nonewline "40..."; flush stdout }
	$ns duplex-link $n(3) $n(54) $linkBW 260ms DropTail
	$ns duplex-link $n(3) $n(52) $linkBW 0ms DropTail
	$ns duplex-link $n(3) $n(48) $linkBW 760ms DropTail
	$ns duplex-link $n(3) $n(4) $linkBW 490ms DropTail
	$ns duplex-link $n(4) $n(794) $linkBW 1600ms DropTail
	$ns duplex-link $n(4) $n(678) $linkBW 1310ms DropTail
	$ns duplex-link $n(4) $n(82) $linkBW 1540ms DropTail
	$ns duplex-link $n(4) $n(611) $linkBW 1470ms DropTail
	$ns duplex-link $n(4) $n(69) $linkBW 860ms DropTail
	$ns duplex-link $n(4) $n(66) $linkBW 430ms DropTail
	if {$verbose} { puts -nonewline "50..."; flush stdout }
	$ns duplex-link $n(4) $n(61) $linkBW 700ms DropTail
	$ns duplex-link $n(4) $n(5) $linkBW 920ms DropTail
	$ns duplex-link $n(5) $n(819) $linkBW 250ms DropTail
	$ns duplex-link $n(5) $n(208) $linkBW 910ms DropTail
	$ns duplex-link $n(5) $n(875) $linkBW 1360ms DropTail
	$ns duplex-link $n(5) $n(76) $linkBW 560ms DropTail
	$ns duplex-link $n(5) $n(72) $linkBW 450ms DropTail
	$ns duplex-link $n(6) $n(7) $linkBW 550ms DropTail
	$ns duplex-link $n(6) $n(9) $linkBW 760ms DropTail
	$ns duplex-link $n(6) $n(10) $linkBW 200ms DropTail
	if {$verbose} { puts -nonewline "60..."; flush stdout }
	$ns duplex-link $n(7) $n(8) $linkBW 680ms DropTail
	$ns duplex-link $n(8) $n(9) $linkBW 80ms DropTail
	$ns duplex-link $n(8) $n(10) $linkBW 580ms DropTail
	$ns duplex-link $n(11) $n(13) $linkBW 910ms DropTail
	$ns duplex-link $n(12) $n(13) $linkBW 200ms DropTail
	$ns duplex-link $n(14) $n(15) $linkBW 600ms DropTail
	$ns duplex-link $n(15) $n(16) $linkBW 230ms DropTail
	$ns duplex-link $n(15) $n(17) $linkBW 500ms DropTail
	$ns duplex-link $n(16) $n(17) $linkBW 610ms DropTail
	$ns duplex-link $n(18) $n(19) $linkBW 240ms DropTail
	if {$verbose} { puts -nonewline "70..."; flush stdout }
	$ns duplex-link $n(20) $n(21) $linkBW 190ms DropTail
	$ns duplex-link $n(20) $n(22) $linkBW 540ms DropTail
	$ns duplex-link $n(23) $n(24) $linkBW 550ms DropTail
	$ns duplex-link $n(23) $n(25) $linkBW 470ms DropTail
	$ns duplex-link $n(23) $n(28) $linkBW 630ms DropTail
	$ns duplex-link $n(23) $n(29) $linkBW 480ms DropTail
	$ns duplex-link $n(24) $n(26) $linkBW 430ms DropTail
	$ns duplex-link $n(24) $n(27) $linkBW 440ms DropTail
	$ns duplex-link $n(25) $n(26) $linkBW 500ms DropTail
	$ns duplex-link $n(26) $n(27) $linkBW 150ms DropTail
	if {$verbose} { puts -nonewline "80..."; flush stdout }
	$ns duplex-link $n(26) $n(28) $linkBW 250ms DropTail
	$ns duplex-link $n(26) $n(29) $linkBW 80ms DropTail
	$ns duplex-link $n(27) $n(29) $linkBW 170ms DropTail
	$ns duplex-link $n(30) $n(32) $linkBW 630ms DropTail
	$ns duplex-link $n(30) $n(33) $linkBW 220ms DropTail
	$ns duplex-link $n(31) $n(32) $linkBW 630ms DropTail
	$ns duplex-link $n(34) $n(36) $linkBW 220ms DropTail
	$ns duplex-link $n(35) $n(36) $linkBW 650ms DropTail
	$ns duplex-link $n(36) $n(37) $linkBW 610ms DropTail
	$ns duplex-link $n(38) $n(41) $linkBW 390ms DropTail
	if {$verbose} { puts -nonewline "90..."; flush stdout }
	$ns duplex-link $n(39) $n(40) $linkBW 200ms DropTail
	$ns duplex-link $n(40) $n(41) $linkBW 700ms DropTail
	$ns duplex-link $n(40) $n(42) $linkBW 380ms DropTail
	$ns duplex-link $n(43) $n(44) $linkBW 680ms DropTail
	$ns duplex-link $n(44) $n(45) $linkBW 190ms DropTail
	$ns duplex-link $n(46) $n(48) $linkBW 510ms DropTail
	$ns duplex-link $n(47) $n(48) $linkBW 640ms DropTail
	$ns duplex-link $n(47) $n(49) $linkBW 260ms DropTail
	$ns duplex-link $n(48) $n(49) $linkBW 450ms DropTail
	$ns duplex-link $n(50) $n(51) $linkBW 520ms DropTail
	if {$verbose} { puts -nonewline "100..."; flush stdout }
	$ns duplex-link $n(50) $n(52) $linkBW 490ms DropTail
	$ns duplex-link $n(51) $n(53) $linkBW 480ms DropTail
	$ns duplex-link $n(52) $n(53) $linkBW 70ms DropTail
	$ns duplex-link $n(54) $n(55) $linkBW 350ms DropTail
	$ns duplex-link $n(54) $n(56) $linkBW 200ms DropTail
	$ns duplex-link $n(54) $n(57) $linkBW 570ms DropTail
	$ns duplex-link $n(55) $n(57) $linkBW 390ms DropTail
	$ns duplex-link $n(58) $n(59) $linkBW 580ms DropTail
	$ns duplex-link $n(58) $n(60) $linkBW 580ms DropTail
	$ns duplex-link $n(59) $n(61) $linkBW 400ms DropTail
	if {$verbose} { puts -nonewline "110..."; flush stdout }
	$ns duplex-link $n(60) $n(61) $linkBW 530ms DropTail
	$ns duplex-link $n(60) $n(62) $linkBW 340ms DropTail
	$ns duplex-link $n(63) $n(64) $linkBW 560ms DropTail
	$ns duplex-link $n(63) $n(66) $linkBW 560ms DropTail
	$ns duplex-link $n(64) $n(65) $linkBW 220ms DropTail
	$ns duplex-link $n(67) $n(69) $linkBW 720ms DropTail
	$ns duplex-link $n(68) $n(69) $linkBW 160ms DropTail
	$ns duplex-link $n(70) $n(72) $linkBW 790ms DropTail
	$ns duplex-link $n(71) $n(72) $linkBW 740ms DropTail
	$ns duplex-link $n(71) $n(73) $linkBW 720ms DropTail
	if {$verbose} { puts -nonewline "120..."; flush stdout }
	$ns duplex-link $n(74) $n(76) $linkBW 860ms DropTail
	$ns duplex-link $n(74) $n(77) $linkBW 320ms DropTail
	$ns duplex-link $n(75) $n(76) $linkBW 680ms DropTail
	$ns duplex-link $n(78) $n(1003) $linkBW 550ms DropTail
	$ns duplex-link $n(78) $n(144) $linkBW 860ms DropTail
	$ns duplex-link $n(78) $n(611) $linkBW 730ms DropTail
	$ns duplex-link $n(78) $n(793) $linkBW 1870ms DropTail
	$ns duplex-link $n(78) $n(821) $linkBW 1470ms DropTail
	$ns duplex-link $n(78) $n(872) $linkBW 1750ms DropTail
	$ns duplex-link $n(78) $n(83) $linkBW 40ms DropTail
	if {$verbose} { puts -nonewline "130..."; flush stdout }
	$ns duplex-link $n(78) $n(79) $linkBW 140ms DropTail
	$ns duplex-link $n(78) $n(81) $linkBW 660ms DropTail
	$ns duplex-link $n(78) $n(82) $linkBW 290ms DropTail
	$ns duplex-link $n(79) $n(470) $linkBW 490ms DropTail
	$ns duplex-link $n(79) $n(210) $linkBW 940ms DropTail
	$ns duplex-link $n(79) $n(624) $linkBW 1780ms DropTail
	$ns duplex-link $n(79) $n(105) $linkBW 790ms DropTail
	$ns duplex-link $n(79) $n(100) $linkBW 750ms DropTail
	$ns duplex-link $n(79) $n(95) $linkBW 710ms DropTail
	$ns duplex-link $n(79) $n(92) $linkBW 480ms DropTail
	if {$verbose} { puts -nonewline "140..."; flush stdout }
	$ns duplex-link $n(79) $n(87) $linkBW 270ms DropTail
	$ns duplex-link $n(79) $n(80) $linkBW 180ms DropTail
	$ns duplex-link $n(80) $n(819) $linkBW 1850ms DropTail
	$ns duplex-link $n(80) $n(611) $linkBW 830ms DropTail
	$ns duplex-link $n(80) $n(275) $linkBW 1050ms DropTail
	$ns duplex-link $n(80) $n(1002) $linkBW 1640ms DropTail
	$ns duplex-link $n(80) $n(110) $linkBW 880ms DropTail
	$ns duplex-link $n(81) $n(952) $linkBW 620ms DropTail
	$ns duplex-link $n(81) $n(793) $linkBW 1440ms DropTail
	$ns duplex-link $n(81) $n(274) $linkBW 840ms DropTail
	if {$verbose} { puts -nonewline "150..."; flush stdout }
	$ns duplex-link $n(81) $n(338) $linkBW 900ms DropTail
	$ns duplex-link $n(81) $n(534) $linkBW 750ms DropTail
	$ns duplex-link $n(81) $n(951) $linkBW 990ms DropTail
	$ns duplex-link $n(81) $n(130) $linkBW 360ms DropTail
	$ns duplex-link $n(81) $n(122) $linkBW 540ms DropTail
	$ns duplex-link $n(81) $n(119) $linkBW 630ms DropTail
	$ns duplex-link $n(81) $n(114) $linkBW 170ms DropTail
	$ns duplex-link $n(81) $n(111) $linkBW 130ms DropTail
	$ns duplex-link $n(82) $n(876) $linkBW 720ms DropTail
	$ns duplex-link $n(82) $n(677) $linkBW 70ms DropTail
	if {$verbose} { puts -nonewline "160..."; flush stdout }
	$ns duplex-link $n(82) $n(627) $linkBW 800ms DropTail
	$ns duplex-link $n(82) $n(536) $linkBW 620ms DropTail
	$ns duplex-link $n(82) $n(339) $linkBW 920ms DropTail
	$ns duplex-link $n(82) $n(144) $linkBW 570ms DropTail
	$ns duplex-link $n(82) $n(212) $linkBW 520ms DropTail
	$ns duplex-link $n(82) $n(469) $linkBW 220ms DropTail
	$ns duplex-link $n(82) $n(684) $linkBW 450ms DropTail
	$ns duplex-link $n(82) $n(141) $linkBW 350ms DropTail
	$ns duplex-link $n(82) $n(139) $linkBW 280ms DropTail
	$ns duplex-link $n(82) $n(132) $linkBW 340ms DropTail
	if {$verbose} { puts -nonewline "170..."; flush stdout }
	$ns duplex-link $n(83) $n(84) $linkBW 670ms DropTail
	$ns duplex-link $n(83) $n(85) $linkBW 460ms DropTail
	$ns duplex-link $n(84) $n(86) $linkBW 450ms DropTail
	$ns duplex-link $n(87) $n(89) $linkBW 350ms DropTail
	$ns duplex-link $n(87) $n(91) $linkBW 310ms DropTail
	$ns duplex-link $n(88) $n(90) $linkBW 610ms DropTail
	$ns duplex-link $n(88) $n(91) $linkBW 220ms DropTail
	$ns duplex-link $n(89) $n(91) $linkBW 90ms DropTail
	$ns duplex-link $n(90) $n(91) $linkBW 530ms DropTail
	$ns duplex-link $n(92) $n(94) $linkBW 660ms DropTail
	if {$verbose} { puts -nonewline "180..."; flush stdout }
	$ns duplex-link $n(93) $n(94) $linkBW 540ms DropTail
	$ns duplex-link $n(95) $n(97) $linkBW 630ms DropTail
	$ns duplex-link $n(96) $n(97) $linkBW 440ms DropTail
	$ns duplex-link $n(98) $n(99) $linkBW 740ms DropTail
	$ns duplex-link $n(98) $n(102) $linkBW 560ms DropTail
	$ns duplex-link $n(98) $n(103) $linkBW 700ms DropTail
	$ns duplex-link $n(99) $n(101) $linkBW 380ms DropTail
	$ns duplex-link $n(99) $n(103) $linkBW 660ms DropTail
	$ns duplex-link $n(100) $n(103) $linkBW 820ms DropTail
	$ns duplex-link $n(101) $n(102) $linkBW 330ms DropTail
	if {$verbose} { puts -nonewline "190..."; flush stdout }
	$ns duplex-link $n(101) $n(103) $linkBW 840ms DropTail
	$ns duplex-link $n(104) $n(105) $linkBW 110ms DropTail
	$ns duplex-link $n(104) $n(106) $linkBW 340ms DropTail
	$ns duplex-link $n(105) $n(106) $linkBW 310ms DropTail
	$ns duplex-link $n(107) $n(108) $linkBW 1170ms DropTail
	$ns duplex-link $n(107) $n(109) $linkBW 660ms DropTail
	$ns duplex-link $n(108) $n(110) $linkBW 950ms DropTail
	$ns duplex-link $n(111) $n(112) $linkBW 190ms DropTail
	$ns duplex-link $n(113) $n(115) $linkBW 560ms DropTail
	$ns duplex-link $n(113) $n(116) $linkBW 160ms DropTail
	if {$verbose} { puts -nonewline "200..."; flush stdout }
	$ns duplex-link $n(113) $n(117) $linkBW 250ms DropTail
	$ns duplex-link $n(114) $n(115) $linkBW 590ms DropTail
	$ns duplex-link $n(115) $n(116) $linkBW 710ms DropTail
	$ns duplex-link $n(115) $n(117) $linkBW 640ms DropTail
	$ns duplex-link $n(118) $n(119) $linkBW 660ms DropTail
	$ns duplex-link $n(120) $n(124) $linkBW 530ms DropTail
	$ns duplex-link $n(121) $n(122) $linkBW 280ms DropTail
	$ns duplex-link $n(121) $n(123) $linkBW 80ms DropTail
	$ns duplex-link $n(121) $n(124) $linkBW 620ms DropTail
	$ns duplex-link $n(121) $n(126) $linkBW 410ms DropTail
	if {$verbose} { puts -nonewline "210..."; flush stdout }
	$ns duplex-link $n(121) $n(128) $linkBW 30ms DropTail
	$ns duplex-link $n(122) $n(123) $linkBW 260ms DropTail
	$ns duplex-link $n(122) $n(126) $linkBW 490ms DropTail
	$ns duplex-link $n(122) $n(127) $linkBW 370ms DropTail
	$ns duplex-link $n(123) $n(124) $linkBW 600ms DropTail
	$ns duplex-link $n(123) $n(125) $linkBW 460ms DropTail
	$ns duplex-link $n(123) $n(127) $linkBW 620ms DropTail
	$ns duplex-link $n(124) $n(127) $linkBW 30ms DropTail
	$ns duplex-link $n(125) $n(126) $linkBW 370ms DropTail
	$ns duplex-link $n(125) $n(128) $linkBW 510ms DropTail
	if {$verbose} { puts -nonewline "220..."; flush stdout }
	$ns duplex-link $n(126) $n(127) $linkBW 780ms DropTail
	$ns duplex-link $n(126) $n(128) $linkBW 390ms DropTail
	$ns duplex-link $n(128) $n(129) $linkBW 310ms DropTail
	$ns duplex-link $n(131) $n(133) $linkBW 350ms DropTail
	$ns duplex-link $n(131) $n(134) $linkBW 720ms DropTail
	$ns duplex-link $n(131) $n(137) $linkBW 210ms DropTail
	$ns duplex-link $n(131) $n(138) $linkBW 550ms DropTail
	$ns duplex-link $n(132) $n(133) $linkBW 360ms DropTail
	$ns duplex-link $n(132) $n(135) $linkBW 480ms DropTail
	$ns duplex-link $n(133) $n(134) $linkBW 380ms DropTail
	if {$verbose} { puts -nonewline "230..."; flush stdout }
	$ns duplex-link $n(133) $n(135) $linkBW 410ms DropTail
	$ns duplex-link $n(133) $n(136) $linkBW 140ms DropTail
	$ns duplex-link $n(133) $n(137) $linkBW 170ms DropTail
	$ns duplex-link $n(133) $n(138) $linkBW 380ms DropTail
	$ns duplex-link $n(134) $n(136) $linkBW 270ms DropTail
	$ns duplex-link $n(135) $n(138) $linkBW 640ms DropTail
	$ns duplex-link $n(137) $n(138) $linkBW 500ms DropTail
	$ns duplex-link $n(140) $n(142) $linkBW 800ms DropTail
	$ns duplex-link $n(141) $n(142) $linkBW 470ms DropTail
	$ns duplex-link $n(143) $n(873) $linkBW 810ms DropTail
	if {$verbose} { puts -nonewline "240..."; flush stdout }
	$ns duplex-link $n(143) $n(611) $linkBW 1450ms DropTail
	$ns duplex-link $n(143) $n(212) $linkBW 950ms DropTail
	$ns duplex-link $n(143) $n(338) $linkBW 770ms DropTail
	$ns duplex-link $n(143) $n(536) $linkBW 610ms DropTail
	$ns duplex-link $n(143) $n(611) $linkBW 1450ms DropTail
	$ns duplex-link $n(143) $n(163) $linkBW 440ms DropTail
	$ns duplex-link $n(143) $n(156) $linkBW 370ms DropTail
	$ns duplex-link $n(143) $n(155) $linkBW 880ms DropTail
	$ns duplex-link $n(143) $n(148) $linkBW 150ms DropTail
	$ns duplex-link $n(143) $n(145) $linkBW 110ms DropTail
	if {$verbose} { puts -nonewline "250..."; flush stdout }
	$ns duplex-link $n(143) $n(146) $linkBW 180ms DropTail
	$ns duplex-link $n(144) $n(819) $linkBW 1710ms DropTail
	$ns duplex-link $n(144) $n(681) $linkBW 520ms DropTail
	$ns duplex-link $n(144) $n(950) $linkBW 380ms DropTail
	$ns duplex-link $n(144) $n(166) $linkBW 640ms DropTail
	$ns duplex-link $n(144) $n(165) $linkBW 450ms DropTail
	$ns duplex-link $n(144) $n(147) $linkBW 650ms DropTail
	$ns duplex-link $n(145) $n(951) $linkBW 790ms DropTail
	$ns duplex-link $n(145) $n(536) $linkBW 510ms DropTail
	$ns duplex-link $n(145) $n(342) $linkBW 130ms DropTail
	if {$verbose} { puts -nonewline "260..."; flush stdout }
	$ns duplex-link $n(145) $n(210) $linkBW 1180ms DropTail
	$ns duplex-link $n(145) $n(684) $linkBW 580ms DropTail
	$ns duplex-link $n(145) $n(178) $linkBW 480ms DropTail
	$ns duplex-link $n(145) $n(173) $linkBW 620ms DropTail
	$ns duplex-link $n(145) $n(146) $linkBW 110ms DropTail
	$ns duplex-link $n(145) $n(147) $linkBW 490ms DropTail
	$ns duplex-link $n(146) $n(626) $linkBW 1130ms DropTail
	$ns duplex-link $n(146) $n(277) $linkBW 310ms DropTail
	$ns duplex-link $n(146) $n(624) $linkBW 1230ms DropTail
	$ns duplex-link $n(146) $n(1003) $linkBW 1170ms DropTail
	if {$verbose} { puts -nonewline "270..."; flush stdout }
	$ns duplex-link $n(146) $n(186) $linkBW 640ms DropTail
	$ns duplex-link $n(146) $n(182) $linkBW 120ms DropTail
	$ns duplex-link $n(146) $n(147) $linkBW 460ms DropTail
	$ns duplex-link $n(147) $n(1003) $linkBW 1100ms DropTail
	$ns duplex-link $n(147) $n(793) $linkBW 2130ms DropTail
	$ns duplex-link $n(147) $n(471) $linkBW 1170ms DropTail
	$ns duplex-link $n(147) $n(276) $linkBW 1190ms DropTail
	$ns duplex-link $n(147) $n(470) $linkBW 710ms DropTail
	$ns duplex-link $n(147) $n(793) $linkBW 2130ms DropTail
	$ns duplex-link $n(147) $n(820) $linkBW 2140ms DropTail
	if {$verbose} { puts -nonewline "280..."; flush stdout }
	$ns duplex-link $n(147) $n(871) $linkBW 1560ms DropTail
	$ns duplex-link $n(147) $n(206) $linkBW 690ms DropTail
	$ns duplex-link $n(147) $n(202) $linkBW 650ms DropTail
	$ns duplex-link $n(147) $n(199) $linkBW 810ms DropTail
	$ns duplex-link $n(147) $n(190) $linkBW 330ms DropTail
	$ns duplex-link $n(147) $n(189) $linkBW 610ms DropTail
	$ns duplex-link $n(148) $n(150) $linkBW 520ms DropTail
	$ns duplex-link $n(148) $n(151) $linkBW 420ms DropTail
	$ns duplex-link $n(148) $n(152) $linkBW 580ms DropTail
	$ns duplex-link $n(148) $n(153) $linkBW 620ms DropTail
	if {$verbose} { puts -nonewline "290..."; flush stdout }
	$ns duplex-link $n(149) $n(152) $linkBW 530ms DropTail
	$ns duplex-link $n(149) $n(153) $linkBW 570ms DropTail
	$ns duplex-link $n(150) $n(151) $linkBW 400ms DropTail
	$ns duplex-link $n(152) $n(153) $linkBW 40ms DropTail
	$ns duplex-link $n(154) $n(155) $linkBW 470ms DropTail
	$ns duplex-link $n(156) $n(157) $linkBW 100ms DropTail
	$ns duplex-link $n(156) $n(158) $linkBW 440ms DropTail
	$ns duplex-link $n(159) $n(161) $linkBW 840ms DropTail
	$ns duplex-link $n(160) $n(162) $linkBW 210ms DropTail
	$ns duplex-link $n(160) $n(163) $linkBW 400ms DropTail
	if {$verbose} { puts -nonewline "300..."; flush stdout }
	$ns duplex-link $n(161) $n(162) $linkBW 420ms DropTail
	$ns duplex-link $n(162) $n(163) $linkBW 610ms DropTail
	$ns duplex-link $n(164) $n(165) $linkBW 130ms DropTail
	$ns duplex-link $n(166) $n(167) $linkBW 50ms DropTail
	$ns duplex-link $n(166) $n(168) $linkBW 620ms DropTail
	$ns duplex-link $n(166) $n(170) $linkBW 830ms DropTail
	$ns duplex-link $n(167) $n(168) $linkBW 570ms DropTail
	$ns duplex-link $n(168) $n(170) $linkBW 230ms DropTail
	$ns duplex-link $n(169) $n(170) $linkBW 640ms DropTail
	$ns duplex-link $n(170) $n(171) $linkBW 550ms DropTail
	if {$verbose} { puts -nonewline "310..."; flush stdout }
	$ns duplex-link $n(172) $n(173) $linkBW 500ms DropTail
	$ns duplex-link $n(173) $n(174) $linkBW 520ms DropTail
	$ns duplex-link $n(173) $n(175) $linkBW 440ms DropTail
	$ns duplex-link $n(176) $n(178) $linkBW 780ms DropTail
	$ns duplex-link $n(176) $n(179) $linkBW 250ms DropTail
	$ns duplex-link $n(177) $n(178) $linkBW 820ms DropTail
	$ns duplex-link $n(177) $n(179) $linkBW 410ms DropTail
	$ns duplex-link $n(180) $n(182) $linkBW 390ms DropTail
	$ns duplex-link $n(180) $n(183) $linkBW 400ms DropTail
	$ns duplex-link $n(181) $n(182) $linkBW 600ms DropTail
	if {$verbose} { puts -nonewline "320..."; flush stdout }
	$ns duplex-link $n(181) $n(183) $linkBW 160ms DropTail
	$ns duplex-link $n(181) $n(184) $linkBW 380ms DropTail
	$ns duplex-link $n(181) $n(185) $linkBW 610ms DropTail
	$ns duplex-link $n(182) $n(183) $linkBW 510ms DropTail
	$ns duplex-link $n(183) $n(185) $linkBW 480ms DropTail
	$ns duplex-link $n(186) $n(187) $linkBW 140ms DropTail
	$ns duplex-link $n(188) $n(189) $linkBW 190ms DropTail
	$ns duplex-link $n(190) $n(192) $linkBW 120ms DropTail
	$ns duplex-link $n(191) $n(193) $linkBW 820ms DropTail
	$ns duplex-link $n(192) $n(193) $linkBW 560ms DropTail
	if {$verbose} { puts -nonewline "330..."; flush stdout }
	$ns duplex-link $n(194) $n(195) $linkBW 340ms DropTail
	$ns duplex-link $n(194) $n(198) $linkBW 290ms DropTail
	$ns duplex-link $n(194) $n(199) $linkBW 740ms DropTail
	$ns duplex-link $n(195) $n(196) $linkBW 520ms DropTail
	$ns duplex-link $n(197) $n(199) $linkBW 810ms DropTail
	$ns duplex-link $n(200) $n(201) $linkBW 470ms DropTail
	$ns duplex-link $n(200) $n(202) $linkBW 120ms DropTail
	$ns duplex-link $n(203) $n(204) $linkBW 390ms DropTail
	$ns duplex-link $n(203) $n(205) $linkBW 260ms DropTail
	$ns duplex-link $n(203) $n(206) $linkBW 170ms DropTail
	if {$verbose} { puts -nonewline "340..."; flush stdout }
	$ns duplex-link $n(204) $n(205) $linkBW 590ms DropTail
	$ns duplex-link $n(204) $n(207) $linkBW 290ms DropTail
	$ns duplex-link $n(208) $n(342) $linkBW 1210ms DropTail
	$ns duplex-link $n(208) $n(819) $linkBW 660ms DropTail
	$ns duplex-link $n(208) $n(214) $linkBW 360ms DropTail
	$ns duplex-link $n(208) $n(209) $linkBW 640ms DropTail
	$ns duplex-link $n(208) $n(210) $linkBW 310ms DropTail
	$ns duplex-link $n(208) $n(212) $linkBW 820ms DropTail
	$ns duplex-link $n(209) $n(949) $linkBW 1440ms DropTail
	$ns duplex-link $n(209) $n(341) $linkBW 1650ms DropTail
	if {$verbose} { puts -nonewline "350..."; flush stdout }
	$ns duplex-link $n(209) $n(537) $linkBW 1970ms DropTail
	$ns duplex-link $n(209) $n(611) $linkBW 850ms DropTail
	$ns duplex-link $n(209) $n(949) $linkBW 1440ms DropTail
	$ns duplex-link $n(209) $n(229) $linkBW 300ms DropTail
	$ns duplex-link $n(209) $n(224) $linkBW 350ms DropTail
	$ns duplex-link $n(209) $n(221) $linkBW 280ms DropTail
	$ns duplex-link $n(209) $n(218) $linkBW 230ms DropTail
	$ns duplex-link $n(209) $n(210) $linkBW 330ms DropTail
	$ns duplex-link $n(209) $n(211) $linkBW 550ms DropTail
	$ns duplex-link $n(209) $n(212) $linkBW 560ms DropTail
	if {$verbose} { puts -nonewline "360..."; flush stdout }
	$ns duplex-link $n(210) $n(1003) $linkBW 320ms DropTail
	$ns duplex-link $n(210) $n(611) $linkBW 1090ms DropTail
	$ns duplex-link $n(210) $n(470) $linkBW 680ms DropTail
	$ns duplex-link $n(210) $n(626) $linkBW 1150ms DropTail
	$ns duplex-link $n(210) $n(682) $linkBW 680ms DropTail
	$ns duplex-link $n(210) $n(1003) $linkBW 320ms DropTail
	$ns duplex-link $n(210) $n(233) $linkBW 300ms DropTail
	$ns duplex-link $n(210) $n(211) $linkBW 310ms DropTail
	$ns duplex-link $n(210) $n(212) $linkBW 640ms DropTail
	$ns duplex-link $n(211) $n(821) $linkBW 960ms DropTail
	if {$verbose} { puts -nonewline "370..."; flush stdout }
	$ns duplex-link $n(211) $n(624) $linkBW 1520ms DropTail
	$ns duplex-link $n(211) $n(537) $linkBW 1450ms DropTail
	$ns duplex-link $n(211) $n(793) $linkBW 1330ms DropTail
	$ns duplex-link $n(211) $n(262) $linkBW 110ms DropTail
	$ns duplex-link $n(211) $n(259) $linkBW 590ms DropTail
	$ns duplex-link $n(211) $n(253) $linkBW 550ms DropTail
	$ns duplex-link $n(211) $n(248) $linkBW 340ms DropTail
	$ns duplex-link $n(211) $n(246) $linkBW 870ms DropTail
	$ns duplex-link $n(211) $n(243) $linkBW 840ms DropTail
	$ns duplex-link $n(211) $n(241) $linkBW 710ms DropTail
	if {$verbose} { puts -nonewline "380..."; flush stdout }
	$ns duplex-link $n(212) $n(875) $linkBW 1700ms DropTail
	$ns duplex-link $n(212) $n(793) $linkBW 1860ms DropTail
	$ns duplex-link $n(212) $n(676) $linkBW 480ms DropTail
	$ns duplex-link $n(212) $n(276) $linkBW 1950ms DropTail
	$ns duplex-link $n(212) $n(273) $linkBW 1870ms DropTail
	$ns duplex-link $n(212) $n(471) $linkBW 560ms DropTail
	$ns duplex-link $n(212) $n(872) $linkBW 1920ms DropTail
	$ns duplex-link $n(212) $n(267) $linkBW 280ms DropTail
	$ns duplex-link $n(212) $n(266) $linkBW 570ms DropTail
	$ns duplex-link $n(213) $n(214) $linkBW 730ms DropTail
	if {$verbose} { puts -nonewline "390..."; flush stdout }
	$ns duplex-link $n(213) $n(216) $linkBW 380ms DropTail
	$ns duplex-link $n(214) $n(215) $linkBW 420ms DropTail
	$ns duplex-link $n(217) $n(219) $linkBW 400ms DropTail
	$ns duplex-link $n(217) $n(220) $linkBW 630ms DropTail
	$ns duplex-link $n(218) $n(220) $linkBW 470ms DropTail
	$ns duplex-link $n(221) $n(222) $linkBW 780ms DropTail
	$ns duplex-link $n(223) $n(224) $linkBW 200ms DropTail
	$ns duplex-link $n(223) $n(225) $linkBW 150ms DropTail
	$ns duplex-link $n(223) $n(226) $linkBW 300ms DropTail
	$ns duplex-link $n(223) $n(227) $linkBW 580ms DropTail
	if {$verbose} { puts -nonewline "400..."; flush stdout }
	$ns duplex-link $n(224) $n(226) $linkBW 430ms DropTail
	$ns duplex-link $n(225) $n(226) $linkBW 370ms DropTail
	$ns duplex-link $n(228) $n(230) $linkBW 70ms DropTail
	$ns duplex-link $n(229) $n(231) $linkBW 540ms DropTail
	$ns duplex-link $n(230) $n(232) $linkBW 400ms DropTail
	$ns duplex-link $n(231) $n(232) $linkBW 720ms DropTail
	$ns duplex-link $n(233) $n(234) $linkBW 230ms DropTail
	$ns duplex-link $n(233) $n(236) $linkBW 800ms DropTail
	$ns duplex-link $n(235) $n(236) $linkBW 100ms DropTail
	$ns duplex-link $n(237) $n(239) $linkBW 630ms DropTail
	if {$verbose} { puts -nonewline "410..."; flush stdout }
	$ns duplex-link $n(238) $n(240) $linkBW 640ms DropTail
	$ns duplex-link $n(239) $n(241) $linkBW 690ms DropTail
	$ns duplex-link $n(240) $n(241) $linkBW 650ms DropTail
	$ns duplex-link $n(242) $n(243) $linkBW 530ms DropTail
	$ns duplex-link $n(242) $n(244) $linkBW 190ms DropTail
	$ns duplex-link $n(243) $n(244) $linkBW 420ms DropTail
	$ns duplex-link $n(245) $n(246) $linkBW 560ms DropTail
	$ns duplex-link $n(246) $n(247) $linkBW 170ms DropTail
	$ns duplex-link $n(249) $n(252) $linkBW 280ms DropTail
	$ns duplex-link $n(249) $n(253) $linkBW 140ms DropTail
	if {$verbose} { puts -nonewline "420..."; flush stdout }
	$ns duplex-link $n(250) $n(253) $linkBW 560ms DropTail
	$ns duplex-link $n(251) $n(252) $linkBW 630ms DropTail
	$ns duplex-link $n(254) $n(257) $linkBW 280ms DropTail
	$ns duplex-link $n(254) $n(258) $linkBW 500ms DropTail
	$ns duplex-link $n(255) $n(257) $linkBW 230ms DropTail
	$ns duplex-link $n(256) $n(258) $linkBW 310ms DropTail
	$ns duplex-link $n(256) $n(259) $linkBW 590ms DropTail
	$ns duplex-link $n(257) $n(258) $linkBW 370ms DropTail
	$ns duplex-link $n(258) $n(260) $linkBW 460ms DropTail
	$ns duplex-link $n(259) $n(260) $linkBW 270ms DropTail
	if {$verbose} { puts -nonewline "430..."; flush stdout }
	$ns duplex-link $n(261) $n(262) $linkBW 820ms DropTail
	$ns duplex-link $n(261) $n(264) $linkBW 530ms DropTail
	$ns duplex-link $n(262) $n(263) $linkBW 550ms DropTail
	$ns duplex-link $n(262) $n(264) $linkBW 730ms DropTail
	$ns duplex-link $n(265) $n(266) $linkBW 400ms DropTail
	$ns duplex-link $n(267) $n(268) $linkBW 690ms DropTail
	$ns duplex-link $n(267) $n(269) $linkBW 670ms DropTail
	$ns duplex-link $n(267) $n(270) $linkBW 440ms DropTail
	$ns duplex-link $n(267) $n(271) $linkBW 590ms DropTail
	$ns duplex-link $n(268) $n(271) $linkBW 300ms DropTail
	if {$verbose} { puts -nonewline "440..."; flush stdout }
	$ns duplex-link $n(268) $n(272) $linkBW 350ms DropTail
	$ns duplex-link $n(270) $n(272) $linkBW 450ms DropTail
	$ns duplex-link $n(273) $n(794) $linkBW 1490ms DropTail
	$ns duplex-link $n(273) $n(611) $linkBW 2260ms DropTail
	$ns duplex-link $n(273) $n(678) $linkBW 1980ms DropTail
	$ns duplex-link $n(273) $n(794) $linkBW 1490ms DropTail
	$ns duplex-link $n(273) $n(822) $linkBW 2230ms DropTail
	$ns duplex-link $n(273) $n(873) $linkBW 1430ms DropTail
	$ns duplex-link $n(273) $n(284) $linkBW 920ms DropTail
	$ns duplex-link $n(273) $n(279) $linkBW 160ms DropTail
	if {$verbose} { puts -nonewline "450..."; flush stdout }
	$ns duplex-link $n(273) $n(276) $linkBW 220ms DropTail
	$ns duplex-link $n(274) $n(1002) $linkBW 2210ms DropTail
	$ns duplex-link $n(274) $n(875) $linkBW 900ms DropTail
	$ns duplex-link $n(274) $n(624) $linkBW 660ms DropTail
	$ns duplex-link $n(274) $n(469) $linkBW 950ms DropTail
	$ns duplex-link $n(274) $n(468) $linkBW 1200ms DropTail
	$ns duplex-link $n(274) $n(534) $linkBW 710ms DropTail
	$ns duplex-link $n(274) $n(286) $linkBW 810ms DropTail
	$ns duplex-link $n(274) $n(276) $linkBW 840ms DropTail
	$ns duplex-link $n(274) $n(277) $linkBW 460ms DropTail
	if {$verbose} { puts -nonewline "460..."; flush stdout }
	$ns duplex-link $n(275) $n(952) $linkBW 280ms DropTail
	$ns duplex-link $n(275) $n(819) $linkBW 1900ms DropTail
	$ns duplex-link $n(275) $n(684) $linkBW 980ms DropTail
	$ns duplex-link $n(275) $n(534) $linkBW 410ms DropTail
	$ns duplex-link $n(275) $n(339) $linkBW 420ms DropTail
	$ns duplex-link $n(275) $n(625) $linkBW 930ms DropTail
	$ns duplex-link $n(275) $n(311) $linkBW 530ms DropTail
	$ns duplex-link $n(275) $n(309) $linkBW 690ms DropTail
	$ns duplex-link $n(275) $n(302) $linkBW 350ms DropTail
	$ns duplex-link $n(275) $n(297) $linkBW 440ms DropTail
	if {$verbose} { puts -nonewline "470..."; flush stdout }
	$ns duplex-link $n(275) $n(293) $linkBW 230ms DropTail
	$ns duplex-link $n(275) $n(290) $linkBW 660ms DropTail
	$ns duplex-link $n(275) $n(277) $linkBW 110ms DropTail
	$ns duplex-link $n(276) $n(611) $linkBW 2290ms DropTail
	$ns duplex-link $n(276) $n(343) $linkBW 680ms DropTail
	$ns duplex-link $n(276) $n(329) $linkBW 910ms DropTail
	$ns duplex-link $n(276) $n(328) $linkBW 680ms DropTail
	$ns duplex-link $n(276) $n(320) $linkBW 360ms DropTail
	$ns duplex-link $n(276) $n(314) $linkBW 340ms DropTail
	$ns duplex-link $n(277) $n(951) $linkBW 450ms DropTail
	if {$verbose} { puts -nonewline "480..."; flush stdout }
	$ns duplex-link $n(277) $n(1002) $linkBW 2000ms DropTail
	$ns duplex-link $n(277) $n(336) $linkBW 630ms DropTail
	$ns duplex-link $n(277) $n(330) $linkBW 200ms DropTail
	$ns duplex-link $n(278) $n(279) $linkBW 290ms DropTail
	$ns duplex-link $n(280) $n(281) $linkBW 230ms DropTail
	$ns duplex-link $n(280) $n(285) $linkBW 420ms DropTail
	$ns duplex-link $n(281) $n(282) $linkBW 330ms DropTail
	$ns duplex-link $n(281) $n(283) $linkBW 670ms DropTail
	$ns duplex-link $n(281) $n(284) $linkBW 750ms DropTail
	$ns duplex-link $n(283) $n(284) $linkBW 690ms DropTail
	if {$verbose} { puts -nonewline "490..."; flush stdout }
	$ns duplex-link $n(286) $n(287) $linkBW 190ms DropTail
	$ns duplex-link $n(286) $n(288) $linkBW 600ms DropTail
	$ns duplex-link $n(287) $n(288) $linkBW 410ms DropTail
	$ns duplex-link $n(287) $n(289) $linkBW 840ms DropTail
	$ns duplex-link $n(291) $n(292) $linkBW 710ms DropTail
	$ns duplex-link $n(291) $n(293) $linkBW 670ms DropTail
	$ns duplex-link $n(291) $n(295) $linkBW 520ms DropTail
	$ns duplex-link $n(292) $n(296) $linkBW 1030ms DropTail
	$ns duplex-link $n(293) $n(294) $linkBW 570ms DropTail
	$ns duplex-link $n(294) $n(295) $linkBW 320ms DropTail
	if {$verbose} { puts -nonewline "500..."; flush stdout }
	$ns duplex-link $n(297) $n(299) $linkBW 260ms DropTail
	$ns duplex-link $n(297) $n(301) $linkBW 530ms DropTail
	$ns duplex-link $n(298) $n(299) $linkBW 290ms DropTail
	$ns duplex-link $n(298) $n(300) $linkBW 510ms DropTail
	$ns duplex-link $n(302) $n(303) $linkBW 330ms DropTail
	$ns duplex-link $n(302) $n(306) $linkBW 850ms DropTail
	$ns duplex-link $n(303) $n(304) $linkBW 500ms DropTail
	$ns duplex-link $n(304) $n(305) $linkBW 340ms DropTail
	$ns duplex-link $n(307) $n(308) $linkBW 730ms DropTail
	$ns duplex-link $n(307) $n(310) $linkBW 830ms DropTail
	if {$verbose} { puts -nonewline "510..."; flush stdout }
	$ns duplex-link $n(308) $n(309) $linkBW 550ms DropTail
	$ns duplex-link $n(308) $n(310) $linkBW 950ms DropTail
	$ns duplex-link $n(311) $n(312) $linkBW 750ms DropTail
	$ns duplex-link $n(312) $n(313) $linkBW 410ms DropTail
	$ns duplex-link $n(314) $n(315) $linkBW 170ms DropTail
	$ns duplex-link $n(314) $n(316) $linkBW 140ms DropTail
	$ns duplex-link $n(317) $n(318) $linkBW 710ms DropTail
	$ns duplex-link $n(317) $n(319) $linkBW 700ms DropTail
	$ns duplex-link $n(317) $n(320) $linkBW 40ms DropTail
	$ns duplex-link $n(318) $n(319) $linkBW 150ms DropTail
	if {$verbose} { puts -nonewline "520..."; flush stdout }
	$ns duplex-link $n(318) $n(322) $linkBW 210ms DropTail
	$ns duplex-link $n(318) $n(323) $linkBW 340ms DropTail
	$ns duplex-link $n(319) $n(321) $linkBW 400ms DropTail
	$ns duplex-link $n(319) $n(323) $linkBW 300ms DropTail
	$ns duplex-link $n(320) $n(321) $linkBW 370ms DropTail
	$ns duplex-link $n(320) $n(324) $linkBW 400ms DropTail
	$ns duplex-link $n(321) $n(323) $linkBW 180ms DropTail
	$ns duplex-link $n(321) $n(324) $linkBW 550ms DropTail
	$ns duplex-link $n(323) $n(324) $linkBW 690ms DropTail
	$ns duplex-link $n(325) $n(328) $linkBW 710ms DropTail
	if {$verbose} { puts -nonewline "530..."; flush stdout }
	$ns duplex-link $n(326) $n(327) $linkBW 930ms DropTail
	$ns duplex-link $n(327) $n(328) $linkBW 930ms DropTail
	$ns duplex-link $n(330) $n(332) $linkBW 40ms DropTail
	$ns duplex-link $n(331) $n(333) $linkBW 390ms DropTail
	$ns duplex-link $n(332) $n(333) $linkBW 240ms DropTail
	$ns duplex-link $n(334) $n(335) $linkBW 700ms DropTail
	$ns duplex-link $n(334) $n(336) $linkBW 470ms DropTail
	$ns duplex-link $n(335) $n(336) $linkBW 580ms DropTail
	$ns duplex-link $n(335) $n(337) $linkBW 350ms DropTail
	$ns duplex-link $n(336) $n(337) $linkBW 270ms DropTail
	if {$verbose} { puts -nonewline "540..."; flush stdout }
	$ns duplex-link $n(338) $n(626) $linkBW 1080ms DropTail
	$ns duplex-link $n(338) $n(538) $linkBW 120ms DropTail
	$ns duplex-link $n(338) $n(359) $linkBW 530ms DropTail
	$ns duplex-link $n(338) $n(353) $linkBW 650ms DropTail
	$ns duplex-link $n(338) $n(348) $linkBW 500ms DropTail
	$ns duplex-link $n(338) $n(339) $linkBW 660ms DropTail
	$ns duplex-link $n(338) $n(341) $linkBW 470ms DropTail
	$ns duplex-link $n(338) $n(345) $linkBW 310ms DropTail
	$ns duplex-link $n(339) $n(1003) $linkBW 1640ms DropTail
	$ns duplex-link $n(339) $n(369) $linkBW 170ms DropTail
	if {$verbose} { puts -nonewline "550..."; flush stdout }
	$ns duplex-link $n(339) $n(363) $linkBW 460ms DropTail
	$ns duplex-link $n(339) $n(360) $linkBW 310ms DropTail
	$ns duplex-link $n(339) $n(342) $linkBW 460ms DropTail
	$ns duplex-link $n(339) $n(344) $linkBW 400ms DropTail
	$ns duplex-link $n(340) $n(679) $linkBW 1680ms DropTail
	$ns duplex-link $n(340) $n(611) $linkBW 2070ms DropTail
	$ns duplex-link $n(340) $n(681) $linkBW 980ms DropTail
	$ns duplex-link $n(340) $n(381) $linkBW 920ms DropTail
	$ns duplex-link $n(340) $n(379) $linkBW 390ms DropTail
	$ns duplex-link $n(340) $n(376) $linkBW 310ms DropTail
	if {$verbose} { puts -nonewline "560..."; flush stdout }
	$ns duplex-link $n(340) $n(342) $linkBW 570ms DropTail
	$ns duplex-link $n(340) $n(346) $linkBW 520ms DropTail
	$ns duplex-link $n(341) $n(793) $linkBW 1660ms DropTail
	$ns duplex-link $n(341) $n(950) $linkBW 440ms DropTail
	$ns duplex-link $n(341) $n(388) $linkBW 800ms DropTail
	$ns duplex-link $n(341) $n(384) $linkBW 730ms DropTail
	$ns duplex-link $n(341) $n(345) $linkBW 570ms DropTail
	$ns duplex-link $n(341) $n(346) $linkBW 200ms DropTail
	$ns duplex-link $n(342) $n(538) $linkBW 610ms DropTail
	$ns duplex-link $n(342) $n(398) $linkBW 150ms DropTail
	if {$verbose} { puts -nonewline "570..."; flush stdout }
	$ns duplex-link $n(342) $n(395) $linkBW 480ms DropTail
	$ns duplex-link $n(342) $n(343) $linkBW 360ms DropTail
	$ns duplex-link $n(342) $n(345) $linkBW 760ms DropTail
	$ns duplex-link $n(342) $n(347) $linkBW 770ms DropTail
	$ns duplex-link $n(343) $n(471) $linkBW 1460ms DropTail
	$ns duplex-link $n(343) $n(469) $linkBW 600ms DropTail
	$ns duplex-link $n(343) $n(794) $linkBW 1310ms DropTail
	$ns duplex-link $n(343) $n(406) $linkBW 180ms DropTail
	$ns duplex-link $n(343) $n(402) $linkBW 530ms DropTail
	$ns duplex-link $n(343) $n(345) $linkBW 650ms DropTail
	if {$verbose} { puts -nonewline "580..."; flush stdout }
	$ns duplex-link $n(344) $n(820) $linkBW 2680ms DropTail
	$ns duplex-link $n(344) $n(627) $linkBW 1240ms DropTail
	$ns duplex-link $n(344) $n(871) $linkBW 1300ms DropTail
	$ns duplex-link $n(344) $n(420) $linkBW 370ms DropTail
	$ns duplex-link $n(344) $n(412) $linkBW 330ms DropTail
	$ns duplex-link $n(344) $n(409) $linkBW 430ms DropTail
	$ns duplex-link $n(344) $n(408) $linkBW 150ms DropTail
	$ns duplex-link $n(344) $n(345) $linkBW 370ms DropTail
	$ns duplex-link $n(345) $n(876) $linkBW 830ms DropTail
	$ns duplex-link $n(345) $n(611) $linkBW 2240ms DropTail
	if {$verbose} { puts -nonewline "590..."; flush stdout }
	$ns duplex-link $n(345) $n(819) $linkBW 2310ms DropTail
	$ns duplex-link $n(345) $n(430) $linkBW 830ms DropTail
	$ns duplex-link $n(345) $n(424) $linkBW 740ms DropTail
	$ns duplex-link $n(346) $n(1002) $linkBW 1810ms DropTail
	$ns duplex-link $n(346) $n(447) $linkBW 850ms DropTail
	$ns duplex-link $n(346) $n(441) $linkBW 150ms DropTail
	$ns duplex-link $n(346) $n(435) $linkBW 630ms DropTail
	$ns duplex-link $n(346) $n(432) $linkBW 350ms DropTail
	$ns duplex-link $n(347) $n(951) $linkBW 150ms DropTail
	$ns duplex-link $n(347) $n(467) $linkBW 490ms DropTail
	if {$verbose} { puts -nonewline "600..."; flush stdout }
	$ns duplex-link $n(347) $n(461) $linkBW 740ms DropTail
	$ns duplex-link $n(347) $n(458) $linkBW 400ms DropTail
	$ns duplex-link $n(347) $n(456) $linkBW 640ms DropTail
	$ns duplex-link $n(347) $n(451) $linkBW 480ms DropTail
	$ns duplex-link $n(349) $n(351) $linkBW 310ms DropTail
	$ns duplex-link $n(349) $n(354) $linkBW 70ms DropTail
	$ns duplex-link $n(350) $n(354) $linkBW 450ms DropTail
	$ns duplex-link $n(351) $n(353) $linkBW 760ms DropTail
	$ns duplex-link $n(351) $n(354) $linkBW 330ms DropTail
	$ns duplex-link $n(352) $n(354) $linkBW 230ms DropTail
	if {$verbose} { puts -nonewline "610..."; flush stdout }
	$ns duplex-link $n(355) $n(357) $linkBW 880ms DropTail
	$ns duplex-link $n(355) $n(358) $linkBW 520ms DropTail
	$ns duplex-link $n(356) $n(357) $linkBW 360ms DropTail
	$ns duplex-link $n(356) $n(359) $linkBW 500ms DropTail
	$ns duplex-link $n(357) $n(359) $linkBW 850ms DropTail
	$ns duplex-link $n(360) $n(361) $linkBW 720ms DropTail
	$ns duplex-link $n(362) $n(363) $linkBW 560ms DropTail
	$ns duplex-link $n(362) $n(364) $linkBW 690ms DropTail
	$ns duplex-link $n(362) $n(365) $linkBW 760ms DropTail
	$ns duplex-link $n(366) $n(368) $linkBW 490ms DropTail
	if {$verbose} { puts -nonewline "620..."; flush stdout }
	$ns duplex-link $n(366) $n(369) $linkBW 280ms DropTail
	$ns duplex-link $n(366) $n(370) $linkBW 520ms DropTail
	$ns duplex-link $n(367) $n(368) $linkBW 210ms DropTail
	$ns duplex-link $n(367) $n(369) $linkBW 710ms DropTail
	$ns duplex-link $n(367) $n(370) $linkBW 780ms DropTail
	$ns duplex-link $n(367) $n(371) $linkBW 110ms DropTail
	$ns duplex-link $n(368) $n(371) $linkBW 150ms DropTail
	$ns duplex-link $n(369) $n(370) $linkBW 250ms DropTail
	$ns duplex-link $n(369) $n(371) $linkBW 620ms DropTail
	$ns duplex-link $n(370) $n(371) $linkBW 720ms DropTail
	if {$verbose} { puts -nonewline "630..."; flush stdout }
	$ns duplex-link $n(372) $n(374) $linkBW 240ms DropTail
	$ns duplex-link $n(373) $n(374) $linkBW 140ms DropTail
	$ns duplex-link $n(373) $n(375) $linkBW 260ms DropTail
	$ns duplex-link $n(373) $n(376) $linkBW 520ms DropTail
	$ns duplex-link $n(374) $n(375) $linkBW 390ms DropTail
	$ns duplex-link $n(374) $n(376) $linkBW 630ms DropTail
	$ns duplex-link $n(377) $n(380) $linkBW 280ms DropTail
	$ns duplex-link $n(378) $n(379) $linkBW 20ms DropTail
	$ns duplex-link $n(378) $n(380) $linkBW 250ms DropTail
	$ns duplex-link $n(381) $n(382) $linkBW 680ms DropTail
	if {$verbose} { puts -nonewline "640..."; flush stdout }
	$ns duplex-link $n(381) $n(383) $linkBW 750ms DropTail
	$ns duplex-link $n(382) $n(383) $linkBW 690ms DropTail
	$ns duplex-link $n(384) $n(385) $linkBW 380ms DropTail
	$ns duplex-link $n(386) $n(388) $linkBW 530ms DropTail
	$ns duplex-link $n(386) $n(390) $linkBW 460ms DropTail
	$ns duplex-link $n(387) $n(389) $linkBW 770ms DropTail
	$ns duplex-link $n(387) $n(391) $linkBW 890ms DropTail
	$ns duplex-link $n(388) $n(389) $linkBW 360ms DropTail
	$ns duplex-link $n(388) $n(390) $linkBW 290ms DropTail
	$ns duplex-link $n(389) $n(391) $linkBW 280ms DropTail
	if {$verbose} { puts -nonewline "650..."; flush stdout }
	$ns duplex-link $n(390) $n(391) $linkBW 350ms DropTail
	$ns duplex-link $n(392) $n(393) $linkBW 420ms DropTail
	$ns duplex-link $n(393) $n(395) $linkBW 190ms DropTail
	$ns duplex-link $n(393) $n(396) $linkBW 300ms DropTail
	$ns duplex-link $n(394) $n(395) $linkBW 170ms DropTail
	$ns duplex-link $n(397) $n(398) $linkBW 400ms DropTail
	$ns duplex-link $n(397) $n(399) $linkBW 400ms DropTail
	$ns duplex-link $n(398) $n(399) $linkBW 600ms DropTail
	$ns duplex-link $n(400) $n(403) $linkBW 770ms DropTail
	$ns duplex-link $n(401) $n(403) $linkBW 900ms DropTail
	if {$verbose} { puts -nonewline "660..."; flush stdout }
	$ns duplex-link $n(402) $n(403) $linkBW 500ms DropTail
	$ns duplex-link $n(404) $n(405) $linkBW 370ms DropTail
	$ns duplex-link $n(404) $n(406) $linkBW 460ms DropTail
	$ns duplex-link $n(405) $n(406) $linkBW 300ms DropTail
	$ns duplex-link $n(405) $n(407) $linkBW 690ms DropTail
	$ns duplex-link $n(409) $n(410) $linkBW 400ms DropTail
	$ns duplex-link $n(411) $n(414) $linkBW 630ms DropTail
	$ns duplex-link $n(411) $n(416) $linkBW 260ms DropTail
	$ns duplex-link $n(412) $n(413) $linkBW 660ms DropTail
	$ns duplex-link $n(412) $n(415) $linkBW 160ms DropTail
	if {$verbose} { puts -nonewline "670..."; flush stdout }
	$ns duplex-link $n(412) $n(419) $linkBW 880ms DropTail
	$ns duplex-link $n(413) $n(416) $linkBW 490ms DropTail
	$ns duplex-link $n(413) $n(419) $linkBW 580ms DropTail
	$ns duplex-link $n(414) $n(416) $linkBW 570ms DropTail
	$ns duplex-link $n(414) $n(418) $linkBW 380ms DropTail
	$ns duplex-link $n(415) $n(418) $linkBW 560ms DropTail
	$ns duplex-link $n(415) $n(419) $linkBW 720ms DropTail
	$ns duplex-link $n(417) $n(418) $linkBW 260ms DropTail
	$ns duplex-link $n(417) $n(419) $linkBW 530ms DropTail
	$ns duplex-link $n(418) $n(419) $linkBW 270ms DropTail
	if {$verbose} { puts -nonewline "680..."; flush stdout }
	$ns duplex-link $n(420) $n(421) $linkBW 790ms DropTail
	$ns duplex-link $n(420) $n(422) $linkBW 920ms DropTail
	$ns duplex-link $n(420) $n(423) $linkBW 60ms DropTail
	$ns duplex-link $n(424) $n(429) $linkBW 660ms DropTail
	$ns duplex-link $n(425) $n(427) $linkBW 490ms DropTail
	$ns duplex-link $n(426) $n(427) $linkBW 200ms DropTail
	$ns duplex-link $n(427) $n(428) $linkBW 230ms DropTail
	$ns duplex-link $n(427) $n(429) $linkBW 410ms DropTail
	$ns duplex-link $n(428) $n(429) $linkBW 610ms DropTail
	$ns duplex-link $n(430) $n(431) $linkBW 670ms DropTail
	if {$verbose} { puts -nonewline "690..."; flush stdout }
	$ns duplex-link $n(433) $n(436) $linkBW 480ms DropTail
	$ns duplex-link $n(434) $n(436) $linkBW 490ms DropTail
	$ns duplex-link $n(434) $n(437) $linkBW 370ms DropTail
	$ns duplex-link $n(435) $n(437) $linkBW 90ms DropTail
	$ns duplex-link $n(438) $n(440) $linkBW 250ms DropTail
	$ns duplex-link $n(439) $n(442) $linkBW 470ms DropTail
	$ns duplex-link $n(440) $n(441) $linkBW 530ms DropTail
	$ns duplex-link $n(441) $n(442) $linkBW 570ms DropTail
	$ns duplex-link $n(441) $n(443) $linkBW 430ms DropTail
	$ns duplex-link $n(444) $n(446) $linkBW 350ms DropTail
	if {$verbose} { puts -nonewline "700..."; flush stdout }
	$ns duplex-link $n(444) $n(447) $linkBW 200ms DropTail
	$ns duplex-link $n(445) $n(446) $linkBW 520ms DropTail
	$ns duplex-link $n(445) $n(447) $linkBW 660ms DropTail
	$ns duplex-link $n(448) $n(449) $linkBW 60ms DropTail
	$ns duplex-link $n(448) $n(451) $linkBW 40ms DropTail
	$ns duplex-link $n(448) $n(453) $linkBW 670ms DropTail
	$ns duplex-link $n(449) $n(450) $linkBW 600ms DropTail
	$ns duplex-link $n(449) $n(453) $linkBW 720ms DropTail
	$ns duplex-link $n(450) $n(451) $linkBW 650ms DropTail
	$ns duplex-link $n(451) $n(454) $linkBW 240ms DropTail
	if {$verbose} { puts -nonewline "710..."; flush stdout }
	$ns duplex-link $n(451) $n(455) $linkBW 330ms DropTail
	$ns duplex-link $n(452) $n(454) $linkBW 260ms DropTail
	$ns duplex-link $n(456) $n(457) $linkBW 570ms DropTail
	$ns duplex-link $n(458) $n(459) $linkBW 270ms DropTail
	$ns duplex-link $n(459) $n(460) $linkBW 380ms DropTail
	$ns duplex-link $n(461) $n(464) $linkBW 810ms DropTail
	$ns duplex-link $n(461) $n(465) $linkBW 520ms DropTail
	$ns duplex-link $n(461) $n(466) $linkBW 590ms DropTail
	$ns duplex-link $n(462) $n(463) $linkBW 540ms DropTail
	$ns duplex-link $n(462) $n(464) $linkBW 510ms DropTail
	if {$verbose} { puts -nonewline "720..."; flush stdout }
	$ns duplex-link $n(462) $n(465) $linkBW 160ms DropTail
	$ns duplex-link $n(463) $n(465) $linkBW 390ms DropTail
	$ns duplex-link $n(464) $n(465) $linkBW 390ms DropTail
	$ns duplex-link $n(464) $n(466) $linkBW 350ms DropTail
	$ns duplex-link $n(468) $n(875) $linkBW 1090ms DropTail
	$ns duplex-link $n(468) $n(793) $linkBW 1320ms DropTail
	$ns duplex-link $n(468) $n(624) $linkBW 1300ms DropTail
	$ns duplex-link $n(468) $n(537) $linkBW 1170ms DropTail
	$ns duplex-link $n(468) $n(793) $linkBW 1320ms DropTail
	$ns duplex-link $n(468) $n(950) $linkBW 530ms DropTail
	if {$verbose} { puts -nonewline "730..."; flush stdout }
	$ns duplex-link $n(468) $n(1003) $linkBW 590ms DropTail
	$ns duplex-link $n(468) $n(475) $linkBW 500ms DropTail
	$ns duplex-link $n(468) $n(470) $linkBW 170ms DropTail
	$ns duplex-link $n(468) $n(471) $linkBW 410ms DropTail
	$ns duplex-link $n(468) $n(472) $linkBW 200ms DropTail
	$ns duplex-link $n(469) $n(822) $linkBW 1340ms DropTail
	$ns duplex-link $n(469) $n(627) $linkBW 640ms DropTail
	$ns duplex-link $n(469) $n(491) $linkBW 540ms DropTail
	$ns duplex-link $n(469) $n(489) $linkBW 310ms DropTail
	$ns duplex-link $n(469) $n(483) $linkBW 350ms DropTail
	if {$verbose} { puts -nonewline "740..."; flush stdout }
	$ns duplex-link $n(469) $n(479) $linkBW 640ms DropTail
	$ns duplex-link $n(469) $n(472) $linkBW 510ms DropTail
	$ns duplex-link $n(470) $n(1001) $linkBW 520ms DropTail
	$ns duplex-link $n(470) $n(611) $linkBW 1100ms DropTail
	$ns duplex-link $n(470) $n(508) $linkBW 350ms DropTail
	$ns duplex-link $n(470) $n(504) $linkBW 440ms DropTail
	$ns duplex-link $n(470) $n(501) $linkBW 390ms DropTail
	$ns duplex-link $n(470) $n(493) $linkBW 90ms DropTail
	$ns duplex-link $n(471) $n(679) $linkBW 360ms DropTail
	$ns duplex-link $n(471) $n(611) $linkBW 1080ms DropTail
	if {$verbose} { puts -nonewline "750..."; flush stdout }
	$ns duplex-link $n(471) $n(538) $linkBW 1600ms DropTail
	$ns duplex-link $n(471) $n(874) $linkBW 1480ms DropTail
	$ns duplex-link $n(471) $n(512) $linkBW 150ms DropTail
	$ns duplex-link $n(472) $n(949) $linkBW 760ms DropTail
	$ns duplex-link $n(472) $n(679) $linkBW 420ms DropTail
	$ns duplex-link $n(472) $n(821) $linkBW 1100ms DropTail
	$ns duplex-link $n(472) $n(528) $linkBW 550ms DropTail
	$ns duplex-link $n(472) $n(525) $linkBW 400ms DropTail
	$ns duplex-link $n(472) $n(521) $linkBW 600ms DropTail
	$ns duplex-link $n(472) $n(518) $linkBW 570ms DropTail
	if {$verbose} { puts -nonewline "760..."; flush stdout }
	$ns duplex-link $n(472) $n(517) $linkBW 610ms DropTail
	$ns duplex-link $n(473) $n(474) $linkBW 220ms DropTail
	$ns duplex-link $n(473) $n(475) $linkBW 290ms DropTail
	$ns duplex-link $n(473) $n(476) $linkBW 250ms DropTail
	$ns duplex-link $n(474) $n(475) $linkBW 250ms DropTail
	$ns duplex-link $n(475) $n(476) $linkBW 410ms DropTail
	$ns duplex-link $n(477) $n(478) $linkBW 590ms DropTail
	$ns duplex-link $n(478) $n(479) $linkBW 580ms DropTail
	$ns duplex-link $n(478) $n(480) $linkBW 20ms DropTail
	$ns duplex-link $n(481) $n(482) $linkBW 340ms DropTail
	if {$verbose} { puts -nonewline "770..."; flush stdout }
	$ns duplex-link $n(481) $n(485) $linkBW 530ms DropTail
	$ns duplex-link $n(481) $n(488) $linkBW 90ms DropTail
	$ns duplex-link $n(482) $n(487) $linkBW 490ms DropTail
	$ns duplex-link $n(483) $n(488) $linkBW 180ms DropTail
	$ns duplex-link $n(484) $n(485) $linkBW 580ms DropTail
	$ns duplex-link $n(484) $n(486) $linkBW 660ms DropTail
	$ns duplex-link $n(484) $n(488) $linkBW 550ms DropTail
	$ns duplex-link $n(485) $n(486) $linkBW 480ms DropTail
	$ns duplex-link $n(486) $n(487) $linkBW 60ms DropTail
	$ns duplex-link $n(486) $n(488) $linkBW 230ms DropTail
	if {$verbose} { puts -nonewline "780..."; flush stdout }
	$ns duplex-link $n(489) $n(490) $linkBW 790ms DropTail
	$ns duplex-link $n(491) $n(492) $linkBW 100ms DropTail
	$ns duplex-link $n(493) $n(495) $linkBW 670ms DropTail
	$ns duplex-link $n(493) $n(497) $linkBW 700ms DropTail
	$ns duplex-link $n(494) $n(495) $linkBW 700ms DropTail
	$ns duplex-link $n(494) $n(498) $linkBW 710ms DropTail
	$ns duplex-link $n(495) $n(498) $linkBW 820ms DropTail
	$ns duplex-link $n(496) $n(497) $linkBW 360ms DropTail
	$ns duplex-link $n(497) $n(498) $linkBW 800ms DropTail
	$ns duplex-link $n(499) $n(501) $linkBW 110ms DropTail
	if {$verbose} { puts -nonewline "790..."; flush stdout }
	$ns duplex-link $n(499) $n(502) $linkBW 390ms DropTail
	$ns duplex-link $n(500) $n(502) $linkBW 950ms DropTail
	$ns duplex-link $n(500) $n(503) $linkBW 130ms DropTail
	$ns duplex-link $n(501) $n(502) $linkBW 490ms DropTail
	$ns duplex-link $n(501) $n(503) $linkBW 400ms DropTail
	$ns duplex-link $n(502) $n(503) $linkBW 890ms DropTail
	$ns duplex-link $n(504) $n(505) $linkBW 690ms DropTail
	$ns duplex-link $n(505) $n(506) $linkBW 890ms DropTail
	$ns duplex-link $n(505) $n(507) $linkBW 510ms DropTail
	$ns duplex-link $n(506) $n(507) $linkBW 710ms DropTail
	if {$verbose} { puts -nonewline "800..."; flush stdout }
	$ns duplex-link $n(509) $n(510) $linkBW 430ms DropTail
	$ns duplex-link $n(509) $n(512) $linkBW 630ms DropTail
	$ns duplex-link $n(510) $n(511) $linkBW 20ms DropTail
	$ns duplex-link $n(513) $n(515) $linkBW 650ms DropTail
	$ns duplex-link $n(514) $n(517) $linkBW 380ms DropTail
	$ns duplex-link $n(515) $n(516) $linkBW 720ms DropTail
	$ns duplex-link $n(516) $n(517) $linkBW 510ms DropTail
	$ns duplex-link $n(518) $n(519) $linkBW 690ms DropTail
	$ns duplex-link $n(520) $n(522) $linkBW 280ms DropTail
	$ns duplex-link $n(520) $n(524) $linkBW 510ms DropTail
	if {$verbose} { puts -nonewline "810..."; flush stdout }
	$ns duplex-link $n(521) $n(524) $linkBW 690ms DropTail
	$ns duplex-link $n(522) $n(523) $linkBW 400ms DropTail
	$ns duplex-link $n(523) $n(524) $linkBW 180ms DropTail
	$ns duplex-link $n(525) $n(526) $linkBW 180ms DropTail
	$ns duplex-link $n(527) $n(529) $linkBW 610ms DropTail
	$ns duplex-link $n(527) $n(530) $linkBW 600ms DropTail
	$ns duplex-link $n(527) $n(531) $linkBW 110ms DropTail
	$ns duplex-link $n(527) $n(532) $linkBW 180ms DropTail
	$ns duplex-link $n(528) $n(530) $linkBW 360ms DropTail
	$ns duplex-link $n(528) $n(532) $linkBW 570ms DropTail
	if {$verbose} { puts -nonewline "820..."; flush stdout }
	$ns duplex-link $n(529) $n(532) $linkBW 610ms DropTail
	$ns duplex-link $n(530) $n(532) $linkBW 540ms DropTail
	$ns duplex-link $n(533) $n(625) $linkBW 1520ms DropTail
	$ns duplex-link $n(533) $n(678) $linkBW 1740ms DropTail
	$ns duplex-link $n(533) $n(819) $linkBW 2480ms DropTail
	$ns duplex-link $n(533) $n(540) $linkBW 450ms DropTail
	$ns duplex-link $n(533) $n(534) $linkBW 340ms DropTail
	$ns duplex-link $n(533) $n(537) $linkBW 600ms DropTail
	$ns duplex-link $n(534) $n(820) $linkBW 2290ms DropTail
	$ns duplex-link $n(534) $n(793) $linkBW 2080ms DropTail
	if {$verbose} { puts -nonewline "830..."; flush stdout }
	$ns duplex-link $n(534) $n(794) $linkBW 1290ms DropTail
	$ns duplex-link $n(534) $n(565) $linkBW 670ms DropTail
	$ns duplex-link $n(534) $n(561) $linkBW 300ms DropTail
	$ns duplex-link $n(534) $n(557) $linkBW 520ms DropTail
	$ns duplex-link $n(534) $n(550) $linkBW 350ms DropTail
	$ns duplex-link $n(534) $n(549) $linkBW 450ms DropTail
	$ns duplex-link $n(534) $n(546) $linkBW 450ms DropTail
	$ns duplex-link $n(534) $n(536) $linkBW 450ms DropTail
	$ns duplex-link $n(534) $n(537) $linkBW 490ms DropTail
	$ns duplex-link $n(535) $n(678) $linkBW 1400ms DropTail
	if {$verbose} { puts -nonewline "840..."; flush stdout }
	$ns duplex-link $n(535) $n(572) $linkBW 610ms DropTail
	$ns duplex-link $n(535) $n(568) $linkBW 460ms DropTail
	$ns duplex-link $n(535) $n(536) $linkBW 650ms DropTail
	$ns duplex-link $n(535) $n(538) $linkBW 390ms DropTail
	$ns duplex-link $n(536) $n(611) $linkBW 1310ms DropTail
	$ns duplex-link $n(536) $n(951) $linkBW 830ms DropTail
	$ns duplex-link $n(536) $n(1002) $linkBW 2040ms DropTail
	$ns duplex-link $n(536) $n(586) $linkBW 170ms DropTail
	$ns duplex-link $n(536) $n(580) $linkBW 260ms DropTail
	$ns duplex-link $n(536) $n(578) $linkBW 790ms DropTail
	if {$verbose} { puts -nonewline "850..."; flush stdout }
	$ns duplex-link $n(536) $n(537) $linkBW 920ms DropTail
	$ns duplex-link $n(536) $n(538) $linkBW 990ms DropTail
	$ns duplex-link $n(537) $n(949) $linkBW 550ms DropTail
	$ns duplex-link $n(537) $n(590) $linkBW 520ms DropTail
	$ns duplex-link $n(538) $n(1002) $linkBW 2230ms DropTail
	$ns duplex-link $n(538) $n(875) $linkBW 1020ms DropTail
	$ns duplex-link $n(538) $n(611) $linkBW 2110ms DropTail
	$ns duplex-link $n(538) $n(624) $linkBW 800ms DropTail
	$ns duplex-link $n(538) $n(874) $linkBW 480ms DropTail
	$ns duplex-link $n(538) $n(607) $linkBW 220ms DropTail
	if {$verbose} { puts -nonewline "860..."; flush stdout }
	$ns duplex-link $n(538) $n(606) $linkBW 450ms DropTail
	$ns duplex-link $n(538) $n(603) $linkBW 330ms DropTail
	$ns duplex-link $n(538) $n(600) $linkBW 180ms DropTail
	$ns duplex-link $n(538) $n(593) $linkBW 490ms DropTail
	$ns duplex-link $n(539) $n(541) $linkBW 830ms DropTail
	$ns duplex-link $n(539) $n(542) $linkBW 700ms DropTail
	$ns duplex-link $n(540) $n(541) $linkBW 420ms DropTail
	$ns duplex-link $n(543) $n(544) $linkBW 540ms DropTail
	$ns duplex-link $n(543) $n(546) $linkBW 620ms DropTail
	$ns duplex-link $n(543) $n(547) $linkBW 600ms DropTail
	if {$verbose} { puts -nonewline "870..."; flush stdout }
	$ns duplex-link $n(544) $n(545) $linkBW 320ms DropTail
	$ns duplex-link $n(544) $n(547) $linkBW 530ms DropTail
	$ns duplex-link $n(545) $n(546) $linkBW 280ms DropTail
	$ns duplex-link $n(545) $n(547) $linkBW 220ms DropTail
	$ns duplex-link $n(546) $n(547) $linkBW 460ms DropTail
	$ns duplex-link $n(548) $n(549) $linkBW 300ms DropTail
	$ns duplex-link $n(550) $n(551) $linkBW 620ms DropTail
	$ns duplex-link $n(550) $n(552) $linkBW 380ms DropTail
	$ns duplex-link $n(550) $n(553) $linkBW 610ms DropTail
	$ns duplex-link $n(551) $n(553) $linkBW 190ms DropTail
	if {$verbose} { puts -nonewline "880..."; flush stdout }
	$ns duplex-link $n(551) $n(554) $linkBW 220ms DropTail
	$ns duplex-link $n(551) $n(556) $linkBW 860ms DropTail
	$ns duplex-link $n(552) $n(553) $linkBW 260ms DropTail
	$ns duplex-link $n(552) $n(555) $linkBW 240ms DropTail
	$ns duplex-link $n(552) $n(556) $linkBW 500ms DropTail
	$ns duplex-link $n(553) $n(556) $linkBW 760ms DropTail
	$ns duplex-link $n(554) $n(555) $linkBW 480ms DropTail
	$ns duplex-link $n(557) $n(558) $linkBW 330ms DropTail
	$ns duplex-link $n(558) $n(559) $linkBW 840ms DropTail
	$ns duplex-link $n(560) $n(562) $linkBW 550ms DropTail
	if {$verbose} { puts -nonewline "890..."; flush stdout }
	$ns duplex-link $n(561) $n(562) $linkBW 420ms DropTail
	$ns duplex-link $n(563) $n(564) $linkBW 370ms DropTail
	$ns duplex-link $n(563) $n(566) $linkBW 730ms DropTail
	$ns duplex-link $n(564) $n(565) $linkBW 240ms DropTail
	$ns duplex-link $n(567) $n(570) $linkBW 610ms DropTail
	$ns duplex-link $n(568) $n(569) $linkBW 850ms DropTail
	$ns duplex-link $n(568) $n(570) $linkBW 540ms DropTail
	$ns duplex-link $n(569) $n(570) $linkBW 720ms DropTail
	$ns duplex-link $n(571) $n(572) $linkBW 220ms DropTail
	$ns duplex-link $n(572) $n(574) $linkBW 170ms DropTail
	if {$verbose} { puts -nonewline "900..."; flush stdout }
	$ns duplex-link $n(573) $n(574) $linkBW 750ms DropTail
	$ns duplex-link $n(575) $n(576) $linkBW 330ms DropTail
	$ns duplex-link $n(575) $n(577) $linkBW 490ms DropTail
	$ns duplex-link $n(575) $n(578) $linkBW 240ms DropTail
	$ns duplex-link $n(576) $n(579) $linkBW 380ms DropTail
	$ns duplex-link $n(578) $n(579) $linkBW 130ms DropTail
	$ns duplex-link $n(580) $n(582) $linkBW 560ms DropTail
	$ns duplex-link $n(581) $n(583) $linkBW 840ms DropTail
	$ns duplex-link $n(582) $n(583) $linkBW 870ms DropTail
	$ns duplex-link $n(582) $n(584) $linkBW 310ms DropTail
	if {$verbose} { puts -nonewline "910..."; flush stdout }
	$ns duplex-link $n(583) $n(584) $linkBW 680ms DropTail
	$ns duplex-link $n(585) $n(586) $linkBW 400ms DropTail
	$ns duplex-link $n(587) $n(588) $linkBW 190ms DropTail
	$ns duplex-link $n(587) $n(589) $linkBW 510ms DropTail
	$ns duplex-link $n(587) $n(590) $linkBW 80ms DropTail
	$ns duplex-link $n(588) $n(589) $linkBW 500ms DropTail
	$ns duplex-link $n(588) $n(590) $linkBW 120ms DropTail
	$ns duplex-link $n(591) $n(592) $linkBW 560ms DropTail
	$ns duplex-link $n(591) $n(595) $linkBW 290ms DropTail
	$ns duplex-link $n(592) $n(593) $linkBW 850ms DropTail
	if {$verbose} { puts -nonewline "920..."; flush stdout }
	$ns duplex-link $n(592) $n(595) $linkBW 370ms DropTail
	$ns duplex-link $n(593) $n(594) $linkBW 220ms DropTail
	$ns duplex-link $n(593) $n(595) $linkBW 490ms DropTail
	$ns duplex-link $n(596) $n(600) $linkBW 390ms DropTail
	$ns duplex-link $n(597) $n(599) $linkBW 410ms DropTail
	$ns duplex-link $n(597) $n(600) $linkBW 170ms DropTail
	$ns duplex-link $n(597) $n(601) $linkBW 390ms DropTail
	$ns duplex-link $n(598) $n(599) $linkBW 840ms DropTail
	$ns duplex-link $n(598) $n(600) $linkBW 400ms DropTail
	$ns duplex-link $n(598) $n(601) $linkBW 730ms DropTail
	if {$verbose} { puts -nonewline "930..."; flush stdout }
	$ns duplex-link $n(599) $n(601) $linkBW 280ms DropTail
	$ns duplex-link $n(600) $n(601) $linkBW 330ms DropTail
	$ns duplex-link $n(602) $n(603) $linkBW 510ms DropTail
	$ns duplex-link $n(603) $n(604) $linkBW 370ms DropTail
	$ns duplex-link $n(605) $n(606) $linkBW 290ms DropTail
	$ns duplex-link $n(607) $n(610) $linkBW 840ms DropTail
	$ns duplex-link $n(608) $n(609) $linkBW 390ms DropTail
	$ns duplex-link $n(609) $n(610) $linkBW 900ms DropTail
	$ns duplex-link $n(611) $n(1002) $linkBW 1450ms DropTail
	$ns duplex-link $n(611) $n(949) $linkBW 1520ms DropTail
	if {$verbose} { puts -nonewline "940..."; flush stdout }
	$ns duplex-link $n(611) $n(875) $linkBW 2280ms DropTail
	$ns duplex-link $n(611) $n(822) $linkBW 1780ms DropTail
	$ns duplex-link $n(611) $n(793) $linkBW 2420ms DropTail
	$ns duplex-link $n(611) $n(682) $linkBW 420ms DropTail
	$ns duplex-link $n(611) $n(625) $linkBW 2380ms DropTail
	$ns duplex-link $n(611) $n(625) $linkBW 2380ms DropTail
	$ns duplex-link $n(611) $n(680) $linkBW 750ms DropTail
	$ns duplex-link $n(611) $n(794) $linkBW 1950ms DropTail
	$ns duplex-link $n(611) $n(819) $linkBW 1930ms DropTail
	$ns duplex-link $n(611) $n(874) $linkBW 2230ms DropTail
	if {$verbose} { puts -nonewline "950..."; flush stdout }
	$ns duplex-link $n(611) $n(952) $linkBW 1680ms DropTail
	$ns duplex-link $n(611) $n(1002) $linkBW 1450ms DropTail
	$ns duplex-link $n(611) $n(620) $linkBW 570ms DropTail
	$ns duplex-link $n(611) $n(619) $linkBW 610ms DropTail
	$ns duplex-link $n(611) $n(617) $linkBW 310ms DropTail
	$ns duplex-link $n(612) $n(613) $linkBW 740ms DropTail
	$ns duplex-link $n(612) $n(615) $linkBW 370ms DropTail
	$ns duplex-link $n(613) $n(614) $linkBW 260ms DropTail
	$ns duplex-link $n(613) $n(617) $linkBW 420ms DropTail
	$ns duplex-link $n(614) $n(615) $linkBW 470ms DropTail
	if {$verbose} { puts -nonewline "960..."; flush stdout }
	$ns duplex-link $n(614) $n(617) $linkBW 220ms DropTail
	$ns duplex-link $n(615) $n(616) $linkBW 420ms DropTail
	$ns duplex-link $n(615) $n(617) $linkBW 480ms DropTail
	$ns duplex-link $n(618) $n(619) $linkBW 410ms DropTail
	$ns duplex-link $n(620) $n(622) $linkBW 790ms DropTail
	$ns duplex-link $n(620) $n(623) $linkBW 800ms DropTail
	$ns duplex-link $n(621) $n(623) $linkBW 220ms DropTail
	$ns duplex-link $n(622) $n(623) $linkBW 260ms DropTail
	$ns duplex-link $n(624) $n(951) $linkBW 1190ms DropTail
	$ns duplex-link $n(624) $n(875) $linkBW 400ms DropTail
	if {$verbose} { puts -nonewline "970..."; flush stdout }
	$ns duplex-link $n(624) $n(820) $linkBW 1730ms DropTail
	$ns duplex-link $n(624) $n(639) $linkBW 100ms DropTail
	$ns duplex-link $n(624) $n(637) $linkBW 360ms DropTail
	$ns duplex-link $n(624) $n(635) $linkBW 520ms DropTail
	$ns duplex-link $n(624) $n(628) $linkBW 150ms DropTail
	$ns duplex-link $n(624) $n(625) $linkBW 150ms DropTail
	$ns duplex-link $n(624) $n(627) $linkBW 700ms DropTail
	$ns duplex-link $n(625) $n(1002) $linkBW 1930ms DropTail
	$ns duplex-link $n(625) $n(793) $linkBW 1000ms DropTail
	$ns duplex-link $n(625) $n(950) $linkBW 760ms DropTail
	if {$verbose} { puts -nonewline "980..."; flush stdout }
	$ns duplex-link $n(625) $n(1001) $linkBW 1640ms DropTail
	$ns duplex-link $n(625) $n(649) $linkBW 650ms DropTail
	$ns duplex-link $n(625) $n(644) $linkBW 320ms DropTail
	$ns duplex-link $n(625) $n(626) $linkBW 510ms DropTail
	$ns duplex-link $n(625) $n(627) $linkBW 620ms DropTail
	$ns duplex-link $n(626) $n(680) $linkBW 1620ms DropTail
	$ns duplex-link $n(626) $n(654) $linkBW 520ms DropTail
	$ns duplex-link $n(627) $n(793) $linkBW 1150ms DropTail
	$ns duplex-link $n(627) $n(684) $linkBW 1160ms DropTail
	$ns duplex-link $n(627) $n(821) $linkBW 780ms DropTail
	if {$verbose} { puts -nonewline "990..."; flush stdout }
	$ns duplex-link $n(627) $n(875) $linkBW 590ms DropTail
	$ns duplex-link $n(627) $n(674) $linkBW 260ms DropTail
	$ns duplex-link $n(627) $n(672) $linkBW 260ms DropTail
	$ns duplex-link $n(627) $n(668) $linkBW 290ms DropTail
	$ns duplex-link $n(627) $n(661) $linkBW 190ms DropTail
	$ns duplex-link $n(627) $n(656) $linkBW 590ms DropTail
	$ns duplex-link $n(628) $n(632) $linkBW 280ms DropTail
	$ns duplex-link $n(628) $n(633) $linkBW 580ms DropTail
	$ns duplex-link $n(629) $n(632) $linkBW 510ms DropTail
	$ns duplex-link $n(630) $n(632) $linkBW 190ms DropTail
	if {$verbose} { puts -nonewline "1000..."; flush stdout }
	$ns duplex-link $n(631) $n(633) $linkBW 410ms DropTail
	$ns duplex-link $n(634) $n(635) $linkBW 630ms DropTail
	$ns duplex-link $n(636) $n(637) $linkBW 730ms DropTail
	$ns duplex-link $n(636) $n(638) $linkBW 830ms DropTail
	$ns duplex-link $n(637) $n(638) $linkBW 360ms DropTail
	$ns duplex-link $n(639) $n(640) $linkBW 420ms DropTail
	$ns duplex-link $n(639) $n(641) $linkBW 500ms DropTail
	$ns duplex-link $n(639) $n(643) $linkBW 620ms DropTail
	$ns duplex-link $n(640) $n(642) $linkBW 510ms DropTail
	$ns duplex-link $n(641) $n(642) $linkBW 470ms DropTail
	if {$verbose} { puts -nonewline "1010..."; flush stdout }
	$ns duplex-link $n(641) $n(643) $linkBW 120ms DropTail
	$ns duplex-link $n(644) $n(647) $linkBW 760ms DropTail
	$ns duplex-link $n(644) $n(648) $linkBW 940ms DropTail
	$ns duplex-link $n(645) $n(646) $linkBW 510ms DropTail
	$ns duplex-link $n(645) $n(647) $linkBW 920ms DropTail
	$ns duplex-link $n(645) $n(648) $linkBW 70ms DropTail
	$ns duplex-link $n(646) $n(648) $linkBW 580ms DropTail
	$ns duplex-link $n(647) $n(648) $linkBW 890ms DropTail
	$ns duplex-link $n(649) $n(651) $linkBW 610ms DropTail
	$ns duplex-link $n(650) $n(651) $linkBW 680ms DropTail
	if {$verbose} { puts -nonewline "1020..."; flush stdout }
	$ns duplex-link $n(652) $n(654) $linkBW 150ms DropTail
	$ns duplex-link $n(652) $n(655) $linkBW 300ms DropTail
	$ns duplex-link $n(653) $n(654) $linkBW 390ms DropTail
	$ns duplex-link $n(653) $n(655) $linkBW 230ms DropTail
	$ns duplex-link $n(656) $n(657) $linkBW 660ms DropTail
	$ns duplex-link $n(658) $n(659) $linkBW 830ms DropTail
	$ns duplex-link $n(658) $n(662) $linkBW 110ms DropTail
	$ns duplex-link $n(659) $n(663) $linkBW 530ms DropTail
	$ns duplex-link $n(660) $n(661) $linkBW 80ms DropTail
	$ns duplex-link $n(660) $n(662) $linkBW 680ms DropTail
	if {$verbose} { puts -nonewline "1030..."; flush stdout }
	$ns duplex-link $n(661) $n(663) $linkBW 420ms DropTail
	$ns duplex-link $n(662) $n(663) $linkBW 400ms DropTail
	$ns duplex-link $n(664) $n(666) $linkBW 430ms DropTail
	$ns duplex-link $n(664) $n(668) $linkBW 290ms DropTail
	$ns duplex-link $n(665) $n(669) $linkBW 240ms DropTail
	$ns duplex-link $n(666) $n(669) $linkBW 550ms DropTail
	$ns duplex-link $n(667) $n(669) $linkBW 510ms DropTail
	$ns duplex-link $n(668) $n(669) $linkBW 210ms DropTail
	$ns duplex-link $n(670) $n(671) $linkBW 110ms DropTail
	$ns duplex-link $n(670) $n(672) $linkBW 550ms DropTail
	if {$verbose} { puts -nonewline "1040..."; flush stdout }
	$ns duplex-link $n(671) $n(672) $linkBW 570ms DropTail
	$ns duplex-link $n(672) $n(673) $linkBW 40ms DropTail
	$ns duplex-link $n(674) $n(675) $linkBW 470ms DropTail
	$ns duplex-link $n(676) $n(950) $linkBW 670ms DropTail
	$ns duplex-link $n(676) $n(874) $linkBW 1250ms DropTail
	$ns duplex-link $n(676) $n(688) $linkBW 290ms DropTail
	$ns duplex-link $n(676) $n(678) $linkBW 640ms DropTail
	$ns duplex-link $n(676) $n(679) $linkBW 640ms DropTail
	$ns duplex-link $n(676) $n(681) $linkBW 270ms DropTail
	$ns duplex-link $n(677) $n(692) $linkBW 730ms DropTail
	if {$verbose} { puts -nonewline "1050..."; flush stdout }
	$ns duplex-link $n(677) $n(681) $linkBW 340ms DropTail
	$ns duplex-link $n(678) $n(1003) $linkBW 490ms DropTail
	$ns duplex-link $n(678) $n(703) $linkBW 550ms DropTail
	$ns duplex-link $n(678) $n(699) $linkBW 130ms DropTail
	$ns duplex-link $n(678) $n(695) $linkBW 690ms DropTail
	$ns duplex-link $n(678) $n(682) $linkBW 210ms DropTail
	$ns duplex-link $n(679) $n(794) $linkBW 1310ms DropTail
	$ns duplex-link $n(679) $n(819) $linkBW 1210ms DropTail
	$ns duplex-link $n(679) $n(872) $linkBW 1940ms DropTail
	$ns duplex-link $n(679) $n(705) $linkBW 230ms DropTail
	if {$verbose} { puts -nonewline "1060..."; flush stdout }
	$ns duplex-link $n(679) $n(680) $linkBW 830ms DropTail
	$ns duplex-link $n(679) $n(681) $linkBW 700ms DropTail
	$ns duplex-link $n(679) $n(682) $linkBW 310ms DropTail
	$ns duplex-link $n(680) $n(820) $linkBW 2060ms DropTail
	$ns duplex-link $n(680) $n(793) $linkBW 2180ms DropTail
	$ns duplex-link $n(680) $n(1003) $linkBW 880ms DropTail
	$ns duplex-link $n(680) $n(723) $linkBW 790ms DropTail
	$ns duplex-link $n(680) $n(720) $linkBW 390ms DropTail
	$ns duplex-link $n(680) $n(717) $linkBW 120ms DropTail
	$ns duplex-link $n(680) $n(710) $linkBW 420ms DropTail
	if {$verbose} { puts -nonewline "1070..."; flush stdout }
	$ns duplex-link $n(681) $n(736) $linkBW 300ms DropTail
	$ns duplex-link $n(681) $n(734) $linkBW 550ms DropTail
	$ns duplex-link $n(681) $n(732) $linkBW 720ms DropTail
	$ns duplex-link $n(681) $n(727) $linkBW 230ms DropTail
	$ns duplex-link $n(681) $n(683) $linkBW 990ms DropTail
	$ns duplex-link $n(682) $n(950) $linkBW 1340ms DropTail
	$ns duplex-link $n(682) $n(752) $linkBW 280ms DropTail
	$ns duplex-link $n(682) $n(748) $linkBW 840ms DropTail
	$ns duplex-link $n(682) $n(747) $linkBW 160ms DropTail
	$ns duplex-link $n(682) $n(742) $linkBW 340ms DropTail
	if {$verbose} { puts -nonewline "1080..."; flush stdout }
	$ns duplex-link $n(682) $n(684) $linkBW 940ms DropTail
	$ns duplex-link $n(683) $n(772) $linkBW 280ms DropTail
	$ns duplex-link $n(683) $n(767) $linkBW 670ms DropTail
	$ns duplex-link $n(683) $n(761) $linkBW 660ms DropTail
	$ns duplex-link $n(683) $n(757) $linkBW 960ms DropTail
	$ns duplex-link $n(683) $n(684) $linkBW 850ms DropTail
	$ns duplex-link $n(684) $n(791) $linkBW 590ms DropTail
	$ns duplex-link $n(684) $n(785) $linkBW 540ms DropTail
	$ns duplex-link $n(684) $n(781) $linkBW 320ms DropTail
	$ns duplex-link $n(684) $n(778) $linkBW 610ms DropTail
	if {$verbose} { puts -nonewline "1090..."; flush stdout }
	$ns duplex-link $n(684) $n(774) $linkBW 400ms DropTail
	$ns duplex-link $n(685) $n(686) $linkBW 620ms DropTail
	$ns duplex-link $n(685) $n(688) $linkBW 340ms DropTail
	$ns duplex-link $n(686) $n(687) $linkBW 760ms DropTail
	$ns duplex-link $n(686) $n(688) $linkBW 510ms DropTail
	$ns duplex-link $n(689) $n(691) $linkBW 420ms DropTail
	$ns duplex-link $n(690) $n(691) $linkBW 360ms DropTail
	$ns duplex-link $n(690) $n(692) $linkBW 670ms DropTail
	$ns duplex-link $n(691) $n(692) $linkBW 480ms DropTail
	$ns duplex-link $n(693) $n(694) $linkBW 80ms DropTail
	if {$verbose} { puts -nonewline "1100..."; flush stdout }
	$ns duplex-link $n(694) $n(695) $linkBW 400ms DropTail
	$ns duplex-link $n(696) $n(699) $linkBW 370ms DropTail
	$ns duplex-link $n(696) $n(701) $linkBW 830ms DropTail
	$ns duplex-link $n(697) $n(698) $linkBW 1170ms DropTail
	$ns duplex-link $n(697) $n(700) $linkBW 340ms DropTail
	$ns duplex-link $n(698) $n(699) $linkBW 500ms DropTail
	$ns duplex-link $n(699) $n(701) $linkBW 490ms DropTail
	$ns duplex-link $n(702) $n(703) $linkBW 490ms DropTail
	$ns duplex-link $n(702) $n(704) $linkBW 320ms DropTail
	$ns duplex-link $n(705) $n(707) $linkBW 840ms DropTail
	if {$verbose} { puts -nonewline "1110..."; flush stdout }
	$ns duplex-link $n(706) $n(707) $linkBW 570ms DropTail
	$ns duplex-link $n(706) $n(708) $linkBW 180ms DropTail
	$ns duplex-link $n(709) $n(712) $linkBW 730ms DropTail
	$ns duplex-link $n(709) $n(713) $linkBW 520ms DropTail
	$ns duplex-link $n(710) $n(711) $linkBW 330ms DropTail
	$ns duplex-link $n(710) $n(712) $linkBW 550ms DropTail
	$ns duplex-link $n(711) $n(712) $linkBW 380ms DropTail
	$ns duplex-link $n(714) $n(717) $linkBW 540ms DropTail
	$ns duplex-link $n(715) $n(716) $linkBW 510ms DropTail
	$ns duplex-link $n(716) $n(718) $linkBW 270ms DropTail
	if {$verbose} { puts -nonewline "1120..."; flush stdout }
	$ns duplex-link $n(717) $n(718) $linkBW 540ms DropTail
	$ns duplex-link $n(719) $n(720) $linkBW 300ms DropTail
	$ns duplex-link $n(719) $n(722) $linkBW 360ms DropTail
	$ns duplex-link $n(720) $n(722) $linkBW 390ms DropTail
	$ns duplex-link $n(721) $n(722) $linkBW 500ms DropTail
	$ns duplex-link $n(723) $n(724) $linkBW 780ms DropTail
	$ns duplex-link $n(725) $n(726) $linkBW 750ms DropTail
	$ns duplex-link $n(725) $n(727) $linkBW 110ms DropTail
	$ns duplex-link $n(726) $n(727) $linkBW 750ms DropTail
	$ns duplex-link $n(728) $n(730) $linkBW 100ms DropTail
	if {$verbose} { puts -nonewline "1130..."; flush stdout }
	$ns duplex-link $n(728) $n(732) $linkBW 740ms DropTail
	$ns duplex-link $n(728) $n(733) $linkBW 620ms DropTail
	$ns duplex-link $n(729) $n(731) $linkBW 140ms DropTail
	$ns duplex-link $n(729) $n(733) $linkBW 720ms DropTail
	$ns duplex-link $n(731) $n(733) $linkBW 760ms DropTail
	$ns duplex-link $n(734) $n(735) $linkBW 50ms DropTail
	$ns duplex-link $n(736) $n(737) $linkBW 740ms DropTail
	$ns duplex-link $n(736) $n(738) $linkBW 650ms DropTail
	$ns duplex-link $n(737) $n(738) $linkBW 280ms DropTail
	$ns duplex-link $n(737) $n(739) $linkBW 470ms DropTail
	if {$verbose} { puts -nonewline "1140..."; flush stdout }
	$ns duplex-link $n(738) $n(740) $linkBW 390ms DropTail
	$ns duplex-link $n(741) $n(743) $linkBW 370ms DropTail
	$ns duplex-link $n(742) $n(743) $linkBW 510ms DropTail
	$ns duplex-link $n(744) $n(746) $linkBW 590ms DropTail
	$ns duplex-link $n(744) $n(747) $linkBW 710ms DropTail
	$ns duplex-link $n(745) $n(746) $linkBW 840ms DropTail
	$ns duplex-link $n(746) $n(747) $linkBW 840ms DropTail
	$ns duplex-link $n(748) $n(749) $linkBW 370ms DropTail
	$ns duplex-link $n(748) $n(750) $linkBW 400ms DropTail
	$ns duplex-link $n(751) $n(752) $linkBW 360ms DropTail
	if {$verbose} { puts -nonewline "1150..."; flush stdout }
	$ns duplex-link $n(751) $n(754) $linkBW 630ms DropTail
	$ns duplex-link $n(751) $n(756) $linkBW 380ms DropTail
	$ns duplex-link $n(753) $n(755) $linkBW 750ms DropTail
	$ns duplex-link $n(753) $n(756) $linkBW 400ms DropTail
	$ns duplex-link $n(754) $n(756) $linkBW 320ms DropTail
	$ns duplex-link $n(757) $n(759) $linkBW 800ms DropTail
	$ns duplex-link $n(758) $n(759) $linkBW 810ms DropTail
	$ns duplex-link $n(759) $n(760) $linkBW 300ms DropTail
	$ns duplex-link $n(762) $n(763) $linkBW 810ms DropTail
	$ns duplex-link $n(763) $n(764) $linkBW 640ms DropTail
	if {$verbose} { puts -nonewline "1160..."; flush stdout }
	$ns duplex-link $n(763) $n(767) $linkBW 750ms DropTail
	$ns duplex-link $n(764) $n(766) $linkBW 270ms DropTail
	$ns duplex-link $n(764) $n(767) $linkBW 120ms DropTail
	$ns duplex-link $n(765) $n(767) $linkBW 110ms DropTail
	$ns duplex-link $n(768) $n(769) $linkBW 320ms DropTail
	$ns duplex-link $n(768) $n(770) $linkBW 250ms DropTail
	$ns duplex-link $n(768) $n(771) $linkBW 300ms DropTail
	$ns duplex-link $n(768) $n(772) $linkBW 190ms DropTail
	$ns duplex-link $n(769) $n(770) $linkBW 540ms DropTail
	$ns duplex-link $n(769) $n(772) $linkBW 470ms DropTail
	if {$verbose} { puts -nonewline "1170..."; flush stdout }
	$ns duplex-link $n(773) $n(774) $linkBW 810ms DropTail
	$ns duplex-link $n(774) $n(776) $linkBW 350ms DropTail
	$ns duplex-link $n(775) $n(776) $linkBW 510ms DropTail
	$ns duplex-link $n(777) $n(778) $linkBW 740ms DropTail
	$ns duplex-link $n(778) $n(779) $linkBW 860ms DropTail
	$ns duplex-link $n(780) $n(781) $linkBW 700ms DropTail
	$ns duplex-link $n(780) $n(784) $linkBW 440ms DropTail
	$ns duplex-link $n(781) $n(782) $linkBW 590ms DropTail
	$ns duplex-link $n(781) $n(783) $linkBW 860ms DropTail
	$ns duplex-link $n(781) $n(784) $linkBW 580ms DropTail
	if {$verbose} { puts -nonewline "1180..."; flush stdout }
	$ns duplex-link $n(782) $n(783) $linkBW 440ms DropTail
	$ns duplex-link $n(782) $n(784) $linkBW 340ms DropTail
	$ns duplex-link $n(783) $n(784) $linkBW 280ms DropTail
	$ns duplex-link $n(785) $n(786) $linkBW 230ms DropTail
	$ns duplex-link $n(785) $n(788) $linkBW 470ms DropTail
	$ns duplex-link $n(786) $n(787) $linkBW 360ms DropTail
	$ns duplex-link $n(786) $n(788) $linkBW 560ms DropTail
	$ns duplex-link $n(787) $n(788) $linkBW 490ms DropTail
	$ns duplex-link $n(789) $n(790) $linkBW 240ms DropTail
	$ns duplex-link $n(789) $n(791) $linkBW 420ms DropTail
	if {$verbose} { puts -nonewline "1190..."; flush stdout }
	$ns duplex-link $n(789) $n(792) $linkBW 110ms DropTail
	$ns duplex-link $n(793) $n(1002) $linkBW 1380ms DropTail
	$ns duplex-link $n(793) $n(821) $linkBW 400ms DropTail
	$ns duplex-link $n(793) $n(874) $linkBW 1310ms DropTail
	$ns duplex-link $n(793) $n(950) $linkBW 1260ms DropTail
	$ns duplex-link $n(793) $n(1003) $linkBW 1650ms DropTail
	$ns duplex-link $n(793) $n(810) $linkBW 380ms DropTail
	$ns duplex-link $n(793) $n(808) $linkBW 520ms DropTail
	$ns duplex-link $n(793) $n(802) $linkBW 250ms DropTail
	$ns duplex-link $n(793) $n(799) $linkBW 700ms DropTail
	if {$verbose} { puts -nonewline "1200..."; flush stdout }
	$ns duplex-link $n(793) $n(794) $linkBW 790ms DropTail
	$ns duplex-link $n(794) $n(951) $linkBW 1350ms DropTail
	$ns duplex-link $n(794) $n(873) $linkBW 70ms DropTail
	$ns duplex-link $n(794) $n(819) $linkBW 1070ms DropTail
	$ns duplex-link $n(794) $n(818) $linkBW 780ms DropTail
	$ns duplex-link $n(794) $n(812) $linkBW 600ms DropTail
	$ns duplex-link $n(795) $n(797) $linkBW 530ms DropTail
	$ns duplex-link $n(795) $n(798) $linkBW 400ms DropTail
	$ns duplex-link $n(795) $n(799) $linkBW 80ms DropTail
	$ns duplex-link $n(796) $n(797) $linkBW 130ms DropTail
	if {$verbose} { puts -nonewline "1210..."; flush stdout }
	$ns duplex-link $n(796) $n(798) $linkBW 230ms DropTail
	$ns duplex-link $n(796) $n(799) $linkBW 690ms DropTail
	$ns duplex-link $n(797) $n(798) $linkBW 140ms DropTail
	$ns duplex-link $n(800) $n(802) $linkBW 670ms DropTail
	$ns duplex-link $n(800) $n(803) $linkBW 510ms DropTail
	$ns duplex-link $n(801) $n(802) $linkBW 410ms DropTail
	$ns duplex-link $n(801) $n(803) $linkBW 430ms DropTail
	$ns duplex-link $n(804) $n(808) $linkBW 650ms DropTail
	$ns duplex-link $n(805) $n(807) $linkBW 440ms DropTail
	$ns duplex-link $n(805) $n(808) $linkBW 920ms DropTail
	if {$verbose} { puts -nonewline "1220..."; flush stdout }
	$ns duplex-link $n(806) $n(807) $linkBW 530ms DropTail
	$ns duplex-link $n(806) $n(809) $linkBW 350ms DropTail
	$ns duplex-link $n(808) $n(809) $linkBW 450ms DropTail
	$ns duplex-link $n(811) $n(812) $linkBW 640ms DropTail
	$ns duplex-link $n(813) $n(815) $linkBW 470ms DropTail
	$ns duplex-link $n(813) $n(816) $linkBW 30ms DropTail
	$ns duplex-link $n(814) $n(815) $linkBW 300ms DropTail
	$ns duplex-link $n(814) $n(816) $linkBW 170ms DropTail
	$ns duplex-link $n(815) $n(816) $linkBW 470ms DropTail
	$ns duplex-link $n(815) $n(818) $linkBW 470ms DropTail
	if {$verbose} { puts -nonewline "1230..."; flush stdout }
	$ns duplex-link $n(816) $n(817) $linkBW 70ms DropTail
	$ns duplex-link $n(819) $n(950) $linkBW 1370ms DropTail
	$ns duplex-link $n(819) $n(830) $linkBW 240ms DropTail
	$ns duplex-link $n(819) $n(829) $linkBW 670ms DropTail
	$ns duplex-link $n(819) $n(825) $linkBW 340ms DropTail
	$ns duplex-link $n(819) $n(820) $linkBW 140ms DropTail
	$ns duplex-link $n(819) $n(821) $linkBW 690ms DropTail
	$ns duplex-link $n(819) $n(822) $linkBW 260ms DropTail
	$ns duplex-link $n(820) $n(872) $linkBW 1920ms DropTail
	$ns duplex-link $n(820) $n(838) $linkBW 460ms DropTail
	if {$verbose} { puts -nonewline "1240..."; flush stdout }
	$ns duplex-link $n(820) $n(835) $linkBW 140ms DropTail
	$ns duplex-link $n(820) $n(821) $linkBW 770ms DropTail
	$ns duplex-link $n(820) $n(822) $linkBW 400ms DropTail
	$ns duplex-link $n(821) $n(858) $linkBW 500ms DropTail
	$ns duplex-link $n(821) $n(852) $linkBW 370ms DropTail
	$ns duplex-link $n(821) $n(849) $linkBW 540ms DropTail
	$ns duplex-link $n(821) $n(846) $linkBW 880ms DropTail
	$ns duplex-link $n(822) $n(1001) $linkBW 890ms DropTail
	$ns duplex-link $n(822) $n(952) $linkBW 1750ms DropTail
	$ns duplex-link $n(822) $n(873) $linkBW 900ms DropTail
	if {$verbose} { puts -nonewline "1250..."; flush stdout }
	$ns duplex-link $n(822) $n(1003) $linkBW 1000ms DropTail
	$ns duplex-link $n(822) $n(868) $linkBW 350ms DropTail
	$ns duplex-link $n(822) $n(866) $linkBW 210ms DropTail
	$ns duplex-link $n(822) $n(861) $linkBW 280ms DropTail
	$ns duplex-link $n(823) $n(824) $linkBW 300ms DropTail
	$ns duplex-link $n(824) $n(825) $linkBW 600ms DropTail
	$ns duplex-link $n(826) $n(828) $linkBW 440ms DropTail
	$ns duplex-link $n(827) $n(829) $linkBW 100ms DropTail
	$ns duplex-link $n(828) $n(829) $linkBW 640ms DropTail
	$ns duplex-link $n(830) $n(833) $linkBW 550ms DropTail
	if {$verbose} { puts -nonewline "1260..."; flush stdout }
	$ns duplex-link $n(831) $n(832) $linkBW 330ms DropTail
	$ns duplex-link $n(832) $n(833) $linkBW 250ms DropTail
	$ns duplex-link $n(833) $n(834) $linkBW 210ms DropTail
	$ns duplex-link $n(835) $n(837) $linkBW 260ms DropTail
	$ns duplex-link $n(836) $n(837) $linkBW 300ms DropTail
	$ns duplex-link $n(838) $n(840) $linkBW 700ms DropTail
	$ns duplex-link $n(838) $n(842) $linkBW 790ms DropTail
	$ns duplex-link $n(839) $n(840) $linkBW 330ms DropTail
	$ns duplex-link $n(839) $n(842) $linkBW 740ms DropTail
	$ns duplex-link $n(840) $n(841) $linkBW 840ms DropTail
	if {$verbose} { puts -nonewline "1270..."; flush stdout }
	$ns duplex-link $n(841) $n(842) $linkBW 640ms DropTail
	$ns duplex-link $n(843) $n(845) $linkBW 440ms DropTail
	$ns duplex-link $n(843) $n(846) $linkBW 840ms DropTail
	$ns duplex-link $n(844) $n(845) $linkBW 220ms DropTail
	$ns duplex-link $n(845) $n(846) $linkBW 560ms DropTail
	$ns duplex-link $n(847) $n(848) $linkBW 230ms DropTail
	$ns duplex-link $n(847) $n(849) $linkBW 670ms DropTail
	$ns duplex-link $n(847) $n(850) $linkBW 550ms DropTail
	$ns duplex-link $n(851) $n(853) $linkBW 40ms DropTail
	$ns duplex-link $n(852) $n(853) $linkBW 590ms DropTail
	if {$verbose} { puts -nonewline "1280..."; flush stdout }
	$ns duplex-link $n(853) $n(854) $linkBW 360ms DropTail
	$ns duplex-link $n(855) $n(858) $linkBW 660ms DropTail
	$ns duplex-link $n(856) $n(857) $linkBW 890ms DropTail
	$ns duplex-link $n(857) $n(858) $linkBW 530ms DropTail
	$ns duplex-link $n(859) $n(860) $linkBW 190ms DropTail
	$ns duplex-link $n(859) $n(861) $linkBW 130ms DropTail
	$ns duplex-link $n(859) $n(863) $linkBW 320ms DropTail
	$ns duplex-link $n(860) $n(861) $linkBW 200ms DropTail
	$ns duplex-link $n(860) $n(863) $linkBW 470ms DropTail
	$ns duplex-link $n(861) $n(862) $linkBW 420ms DropTail
	if {$verbose} { puts -nonewline "1290..."; flush stdout }
	$ns duplex-link $n(864) $n(865) $linkBW 420ms DropTail
	$ns duplex-link $n(865) $n(866) $linkBW 240ms DropTail
	$ns duplex-link $n(867) $n(869) $linkBW 490ms DropTail
	$ns duplex-link $n(868) $n(870) $linkBW 980ms DropTail
	$ns duplex-link $n(869) $n(870) $linkBW 450ms DropTail
	$ns duplex-link $n(871) $n(883) $linkBW 840ms DropTail
	$ns duplex-link $n(871) $n(878) $linkBW 420ms DropTail
	$ns duplex-link $n(871) $n(874) $linkBW 220ms DropTail
	$ns duplex-link $n(871) $n(875) $linkBW 400ms DropTail
	$ns duplex-link $n(871) $n(876) $linkBW 650ms DropTail
	if {$verbose} { puts -nonewline "1300..."; flush stdout }
	$ns duplex-link $n(872) $n(951) $linkBW 1010ms DropTail
	$ns duplex-link $n(872) $n(896) $linkBW 240ms DropTail
	$ns duplex-link $n(872) $n(892) $linkBW 1020ms DropTail
	$ns duplex-link $n(872) $n(887) $linkBW 630ms DropTail
	$ns duplex-link $n(872) $n(886) $linkBW 280ms DropTail
	$ns duplex-link $n(872) $n(874) $linkBW 250ms DropTail
	$ns duplex-link $n(873) $n(905) $linkBW 190ms DropTail
	$ns duplex-link $n(873) $n(904) $linkBW 660ms DropTail
	$ns duplex-link $n(873) $n(875) $linkBW 310ms DropTail
	$ns duplex-link $n(874) $n(1003) $linkBW 1710ms DropTail
	if {$verbose} { puts -nonewline "1310..."; flush stdout }
	$ns duplex-link $n(874) $n(1002) $linkBW 2030ms DropTail
	$ns duplex-link $n(874) $n(916) $linkBW 210ms DropTail
	$ns duplex-link $n(874) $n(911) $linkBW 720ms DropTail
	$ns duplex-link $n(875) $n(952) $linkBW 1290ms DropTail
	$ns duplex-link $n(875) $n(935) $linkBW 340ms DropTail
	$ns duplex-link $n(875) $n(932) $linkBW 710ms DropTail
	$ns duplex-link $n(875) $n(928) $linkBW 120ms DropTail
	$ns duplex-link $n(875) $n(918) $linkBW 700ms DropTail
	$ns duplex-link $n(875) $n(917) $linkBW 440ms DropTail
	$ns duplex-link $n(875) $n(876) $linkBW 740ms DropTail
	if {$verbose} { puts -nonewline "1320..."; flush stdout }
	$ns duplex-link $n(876) $n(947) $linkBW 350ms DropTail
	$ns duplex-link $n(876) $n(938) $linkBW 200ms DropTail
	$ns duplex-link $n(876) $n(937) $linkBW 830ms DropTail
	$ns duplex-link $n(877) $n(878) $linkBW 240ms DropTail
	$ns duplex-link $n(877) $n(880) $linkBW 330ms DropTail
	$ns duplex-link $n(878) $n(880) $linkBW 520ms DropTail
	$ns duplex-link $n(878) $n(881) $linkBW 60ms DropTail
	$ns duplex-link $n(879) $n(880) $linkBW 680ms DropTail
	$ns duplex-link $n(879) $n(881) $linkBW 500ms DropTail
	$ns duplex-link $n(879) $n(882) $linkBW 870ms DropTail
	if {$verbose} { puts -nonewline "1330..."; flush stdout }
	$ns duplex-link $n(880) $n(881) $linkBW 570ms DropTail
	$ns duplex-link $n(883) $n(884) $linkBW 690ms DropTail
	$ns duplex-link $n(885) $n(886) $linkBW 480ms DropTail
	$ns duplex-link $n(887) $n(889) $linkBW 140ms DropTail
	$ns duplex-link $n(888) $n(889) $linkBW 480ms DropTail
	$ns duplex-link $n(890) $n(892) $linkBW 560ms DropTail
	$ns duplex-link $n(890) $n(893) $linkBW 300ms DropTail
	$ns duplex-link $n(891) $n(892) $linkBW 810ms DropTail
	$ns duplex-link $n(891) $n(893) $linkBW 740ms DropTail
	$ns duplex-link $n(892) $n(893) $linkBW 260ms DropTail
	if {$verbose} { puts -nonewline "1340..."; flush stdout }
	$ns duplex-link $n(894) $n(895) $linkBW 260ms DropTail
	$ns duplex-link $n(894) $n(899) $linkBW 250ms DropTail
	$ns duplex-link $n(895) $n(896) $linkBW 90ms DropTail
	$ns duplex-link $n(895) $n(898) $linkBW 580ms DropTail
	$ns duplex-link $n(895) $n(899) $linkBW 490ms DropTail
	$ns duplex-link $n(896) $n(897) $linkBW 700ms DropTail
	$ns duplex-link $n(896) $n(898) $linkBW 550ms DropTail
	$ns duplex-link $n(896) $n(899) $linkBW 430ms DropTail
	$ns duplex-link $n(897) $n(898) $linkBW 220ms DropTail
	$ns duplex-link $n(899) $n(900) $linkBW 400ms DropTail
	if {$verbose} { puts -nonewline "1350..."; flush stdout }
	$ns duplex-link $n(901) $n(902) $linkBW 170ms DropTail
	$ns duplex-link $n(901) $n(903) $linkBW 580ms DropTail
	$ns duplex-link $n(903) $n(904) $linkBW 650ms DropTail
	$ns duplex-link $n(905) $n(908) $linkBW 340ms DropTail
	$ns duplex-link $n(906) $n(908) $linkBW 230ms DropTail
	$ns duplex-link $n(907) $n(908) $linkBW 340ms DropTail
	$ns duplex-link $n(909) $n(910) $linkBW 110ms DropTail
	$ns duplex-link $n(909) $n(911) $linkBW 900ms DropTail
	$ns duplex-link $n(910) $n(912) $linkBW 910ms DropTail
	$ns duplex-link $n(913) $n(914) $linkBW 130ms DropTail
	if {$verbose} { puts -nonewline "1360..."; flush stdout }
	$ns duplex-link $n(913) $n(915) $linkBW 760ms DropTail
	$ns duplex-link $n(913) $n(916) $linkBW 670ms DropTail
	$ns duplex-link $n(918) $n(919) $linkBW 140ms DropTail
	$ns duplex-link $n(918) $n(920) $linkBW 600ms DropTail
	$ns duplex-link $n(918) $n(921) $linkBW 730ms DropTail
	$ns duplex-link $n(918) $n(922) $linkBW 560ms DropTail
	$ns duplex-link $n(919) $n(921) $linkBW 610ms DropTail
	$ns duplex-link $n(919) $n(922) $linkBW 420ms DropTail
	$ns duplex-link $n(920) $n(923) $linkBW 100ms DropTail
	$ns duplex-link $n(921) $n(923) $linkBW 120ms DropTail
	if {$verbose} { puts -nonewline "1370..."; flush stdout }
	$ns duplex-link $n(922) $n(924) $linkBW 300ms DropTail
	$ns duplex-link $n(923) $n(924) $linkBW 570ms DropTail
	$ns duplex-link $n(925) $n(926) $linkBW 750ms DropTail
	$ns duplex-link $n(926) $n(928) $linkBW 530ms DropTail
	$ns duplex-link $n(926) $n(929) $linkBW 570ms DropTail
	$ns duplex-link $n(927) $n(928) $linkBW 510ms DropTail
	$ns duplex-link $n(928) $n(929) $linkBW 220ms DropTail
	$ns duplex-link $n(930) $n(931) $linkBW 130ms DropTail
	$ns duplex-link $n(931) $n(932) $linkBW 190ms DropTail
	$ns duplex-link $n(933) $n(934) $linkBW 360ms DropTail
	if {$verbose} { puts -nonewline "1380..."; flush stdout }
	$ns duplex-link $n(933) $n(935) $linkBW 510ms DropTail
	$ns duplex-link $n(934) $n(936) $linkBW 230ms DropTail
	$ns duplex-link $n(938) $n(941) $linkBW 280ms DropTail
	$ns duplex-link $n(938) $n(944) $linkBW 290ms DropTail
	$ns duplex-link $n(939) $n(943) $linkBW 220ms DropTail
	$ns duplex-link $n(939) $n(945) $linkBW 710ms DropTail
	$ns duplex-link $n(940) $n(941) $linkBW 250ms DropTail
	$ns duplex-link $n(940) $n(944) $linkBW 160ms DropTail
	$ns duplex-link $n(940) $n(945) $linkBW 550ms DropTail
	$ns duplex-link $n(941) $n(942) $linkBW 500ms DropTail
	if {$verbose} { puts -nonewline "1390..."; flush stdout }
	$ns duplex-link $n(941) $n(944) $linkBW 400ms DropTail
	$ns duplex-link $n(941) $n(945) $linkBW 800ms DropTail
	$ns duplex-link $n(942) $n(943) $linkBW 180ms DropTail
	$ns duplex-link $n(943) $n(944) $linkBW 210ms DropTail
	$ns duplex-link $n(944) $n(945) $linkBW 410ms DropTail
	$ns duplex-link $n(946) $n(947) $linkBW 460ms DropTail
	$ns duplex-link $n(946) $n(948) $linkBW 830ms DropTail
	$ns duplex-link $n(947) $n(948) $linkBW 460ms DropTail
	$ns duplex-link $n(949) $n(1001) $linkBW 1110ms DropTail
	$ns duplex-link $n(949) $n(957) $linkBW 300ms DropTail
	if {$verbose} { puts -nonewline "1400..."; flush stdout }
	$ns duplex-link $n(949) $n(953) $linkBW 760ms DropTail
	$ns duplex-link $n(949) $n(950) $linkBW 400ms DropTail
	$ns duplex-link $n(949) $n(951) $linkBW 690ms DropTail
	$ns duplex-link $n(950) $n(978) $linkBW 690ms DropTail
	$ns duplex-link $n(950) $n(971) $linkBW 540ms DropTail
	$ns duplex-link $n(950) $n(968) $linkBW 520ms DropTail
	$ns duplex-link $n(950) $n(965) $linkBW 760ms DropTail
	$ns duplex-link $n(950) $n(964) $linkBW 290ms DropTail
	$ns duplex-link $n(950) $n(952) $linkBW 670ms DropTail
	$ns duplex-link $n(951) $n(1001) $linkBW 1800ms DropTail
	if {$verbose} { puts -nonewline "1410..."; flush stdout }
	$ns duplex-link $n(951) $n(983) $linkBW 710ms DropTail
	$ns duplex-link $n(951) $n(952) $linkBW 420ms DropTail
	$ns duplex-link $n(952) $n(999) $linkBW 180ms DropTail
	$ns duplex-link $n(952) $n(995) $linkBW 470ms DropTail
	$ns duplex-link $n(952) $n(993) $linkBW 350ms DropTail
	$ns duplex-link $n(952) $n(985) $linkBW 360ms DropTail
	$ns duplex-link $n(954) $n(955) $linkBW 260ms DropTail
	$ns duplex-link $n(955) $n(956) $linkBW 540ms DropTail
	$ns duplex-link $n(955) $n(959) $linkBW 320ms DropTail
	$ns duplex-link $n(955) $n(960) $linkBW 350ms DropTail
	if {$verbose} { puts -nonewline "1420..."; flush stdout }
	$ns duplex-link $n(956) $n(958) $linkBW 390ms DropTail
	$ns duplex-link $n(956) $n(959) $linkBW 280ms DropTail
	$ns duplex-link $n(957) $n(960) $linkBW 760ms DropTail
	$ns duplex-link $n(958) $n(960) $linkBW 740ms DropTail
	$ns duplex-link $n(959) $n(960) $linkBW 350ms DropTail
	$ns duplex-link $n(961) $n(962) $linkBW 640ms DropTail
	$ns duplex-link $n(961) $n(964) $linkBW 40ms DropTail
	$ns duplex-link $n(963) $n(964) $linkBW 490ms DropTail
	$ns duplex-link $n(966) $n(967) $linkBW 290ms DropTail
	$ns duplex-link $n(967) $n(968) $linkBW 730ms DropTail
	if {$verbose} { puts -nonewline "1430..."; flush stdout }
	$ns duplex-link $n(967) $n(969) $linkBW 280ms DropTail
	$ns duplex-link $n(968) $n(969) $linkBW 510ms DropTail
	$ns duplex-link $n(970) $n(973) $linkBW 410ms DropTail
	$ns duplex-link $n(970) $n(975) $linkBW 790ms DropTail
	$ns duplex-link $n(970) $n(976) $linkBW 550ms DropTail
	$ns duplex-link $n(971) $n(972) $linkBW 500ms DropTail
	$ns duplex-link $n(971) $n(973) $linkBW 510ms DropTail
	$ns duplex-link $n(971) $n(974) $linkBW 230ms DropTail
	$ns duplex-link $n(971) $n(975) $linkBW 820ms DropTail
	$ns duplex-link $n(971) $n(976) $linkBW 200ms DropTail
	if {$verbose} { puts -nonewline "1440..."; flush stdout }
	$ns duplex-link $n(972) $n(973) $linkBW 630ms DropTail
	$ns duplex-link $n(972) $n(975) $linkBW 690ms DropTail
	$ns duplex-link $n(973) $n(975) $linkBW 380ms DropTail
	$ns duplex-link $n(974) $n(975) $linkBW 810ms DropTail
	$ns duplex-link $n(975) $n(976) $linkBW 960ms DropTail
	$ns duplex-link $n(977) $n(978) $linkBW 360ms DropTail
	$ns duplex-link $n(978) $n(979) $linkBW 390ms DropTail
	$ns duplex-link $n(978) $n(980) $linkBW 460ms DropTail
	$ns duplex-link $n(979) $n(980) $linkBW 300ms DropTail
	$ns duplex-link $n(981) $n(982) $linkBW 480ms DropTail
	if {$verbose} { puts -nonewline "1450..."; flush stdout }
	$ns duplex-link $n(982) $n(983) $linkBW 740ms DropTail
	$ns duplex-link $n(982) $n(984) $linkBW 380ms DropTail
	$ns duplex-link $n(983) $n(984) $linkBW 1000ms DropTail
	$ns duplex-link $n(985) $n(986) $linkBW 300ms DropTail
	$ns duplex-link $n(985) $n(987) $linkBW 340ms DropTail
	$ns duplex-link $n(985) $n(990) $linkBW 640ms DropTail
	$ns duplex-link $n(986) $n(987) $linkBW 410ms DropTail
	$ns duplex-link $n(986) $n(989) $linkBW 320ms DropTail
	$ns duplex-link $n(986) $n(991) $linkBW 670ms DropTail
	$ns duplex-link $n(987) $n(990) $linkBW 530ms DropTail
	if {$verbose} { puts -nonewline "1460..."; flush stdout }
	$ns duplex-link $n(987) $n(991) $linkBW 270ms DropTail
	$ns duplex-link $n(988) $n(989) $linkBW 260ms DropTail
	$ns duplex-link $n(988) $n(991) $linkBW 580ms DropTail
	$ns duplex-link $n(989) $n(990) $linkBW 590ms DropTail
	$ns duplex-link $n(992) $n(994) $linkBW 280ms DropTail
	$ns duplex-link $n(993) $n(994) $linkBW 370ms DropTail
	$ns duplex-link $n(995) $n(996) $linkBW 560ms DropTail
	$ns duplex-link $n(995) $n(997) $linkBW 840ms DropTail
	$ns duplex-link $n(995) $n(998) $linkBW 440ms DropTail
	$ns duplex-link $n(997) $n(998) $linkBW 510ms DropTail
	if {$verbose} { puts -nonewline "1470..."; flush stdout }
	$ns duplex-link $n(999) $n(1000) $linkBW 250ms DropTail
	$ns duplex-link $n(1001) $n(1022) $linkBW 230ms DropTail
	$ns duplex-link $n(1001) $n(1018) $linkBW 120ms DropTail
	$ns duplex-link $n(1001) $n(1016) $linkBW 620ms DropTail
	$ns duplex-link $n(1001) $n(1014) $linkBW 20ms DropTail
	$ns duplex-link $n(1001) $n(1004) $linkBW 450ms DropTail
	$ns duplex-link $n(1001) $n(1002) $linkBW 760ms DropTail
	$ns duplex-link $n(1002) $n(1028) $linkBW 190ms DropTail
	$ns duplex-link $n(1002) $n(1026) $linkBW 590ms DropTail
	$ns duplex-link $n(1002) $n(1003) $linkBW 790ms DropTail
	if {$verbose} { puts -nonewline "1480..."; flush stdout }
	$ns duplex-link $n(1003) $n(1038) $linkBW 210ms DropTail
	$ns duplex-link $n(1003) $n(1034) $linkBW 560ms DropTail
	$ns duplex-link $n(1004) $n(1006) $linkBW 750ms DropTail
	$ns duplex-link $n(1004) $n(1007) $linkBW 810ms DropTail
	$ns duplex-link $n(1004) $n(1008) $linkBW 1130ms DropTail
	$ns duplex-link $n(1004) $n(1009) $linkBW 1040ms DropTail
	$ns duplex-link $n(1005) $n(1006) $linkBW 570ms DropTail
	$ns duplex-link $n(1006) $n(1008) $linkBW 750ms DropTail
	$ns duplex-link $n(1008) $n(1009) $linkBW 130ms DropTail
	$ns duplex-link $n(1010) $n(1012) $linkBW 840ms DropTail
	if {$verbose} { puts -nonewline "1490..."; flush stdout }
	$ns duplex-link $n(1010) $n(1013) $linkBW 840ms DropTail
	$ns duplex-link $n(1010) $n(1015) $linkBW 430ms DropTail
	$ns duplex-link $n(1011) $n(1013) $linkBW 320ms DropTail
	$ns duplex-link $n(1013) $n(1015) $linkBW 670ms DropTail
	$ns duplex-link $n(1014) $n(1015) $linkBW 410ms DropTail
	$ns duplex-link $n(1017) $n(1018) $linkBW 410ms DropTail
	$ns duplex-link $n(1019) $n(1021) $linkBW 470ms DropTail
	$ns duplex-link $n(1019) $n(1022) $linkBW 350ms DropTail
	$ns duplex-link $n(1020) $n(1021) $linkBW 260ms DropTail
	$ns duplex-link $n(1021) $n(1023) $linkBW 470ms DropTail
	if {$verbose} { puts -nonewline "1500..."; flush stdout }
	$ns duplex-link $n(1022) $n(1023) $linkBW 430ms DropTail
	$ns duplex-link $n(1024) $n(1027) $linkBW 780ms DropTail
	$ns duplex-link $n(1025) $n(1027) $linkBW 120ms DropTail
	$ns duplex-link $n(1026) $n(1027) $linkBW 200ms DropTail
	$ns duplex-link $n(1028) $n(1029) $linkBW 490ms DropTail
	$ns duplex-link $n(1028) $n(1030) $linkBW 560ms DropTail
	$ns duplex-link $n(1029) $n(1030) $linkBW 200ms DropTail
	$ns duplex-link $n(1029) $n(1031) $linkBW 300ms DropTail
	$ns duplex-link $n(1032) $n(1034) $linkBW 10ms DropTail
	$ns duplex-link $n(1032) $n(1035) $linkBW 140ms DropTail
	if {$verbose} { puts -nonewline "1510..."; flush stdout }
	$ns duplex-link $n(1033) $n(1035) $linkBW 950ms DropTail
	$ns duplex-link $n(1034) $n(1035) $linkBW 150ms DropTail
	$ns duplex-link $n(1036) $n(1037) $linkBW 360ms DropTail
	$ns duplex-link $n(1037) $n(1039) $linkBW 560ms DropTail
	$ns duplex-link $n(1038) $n(1039) $linkBW 570ms DropTail

	if {$verbose} { 
		puts -nonewline "1515..."
		flush stdout
		puts "starting"
	}
	return 1040
}


